### ISSUE TITLE
Bug: Deleted Virtual Node remains in route target list

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#103]
**Summary**

When a Virtual Node which is a target of a Route is deleted, the route still points to the Virtual Node. This will result in traffic still being routed to that Virtual Node. If the compute resource serving that Virtual Node is still online, it may continue to receive the traffic. If the compute resource is no longer online, downstream clients may continue to route and send traffic to last known endpoints cached locally. Downstream clients may also re-balance and shift traffic to the remaining Virtual Nodes in the route if using weighted targets. 

**Steps to reproduce**

1. Create a Mesh, Virtual Node, and Virtual Router.
2. Create a Route under the Virtual Router that points to the Virtual Node as a target.
3. Delete the Virtual Node

Expected: You cannot delete the Virtual Node because it is being targeted by a Route.
Actual: The Virtual Node is deleted, and the Route erroneously points to it as a target.

**Workaround**

To work around this issue, first remove the Virtual Node as a target from the Route, then delete the Virtual Node.

**Comment by rajal-amzn** [comment]
Before deleting a Virtual Node, we need to check for all the route target references and if there are, we should disallow the operation. We are working on the fix.

**Comment by rajal-amzn** [comment]
This needs a backfill of data to store references of route targets from Virtual Nodes. We are working on the backfill now.

**Comment by andrnj** [comment]
We've made significant progress on resolving this issue.

There's one known edge case remaining, where users who create a new Virtual Node with the same name as a deleted Virtual Node with attached Route(s) can get into this state. Users in this state will still need to apply the work-around.

We have a solution to this edge-case and are working to ensure that this issue is resolved completely.

**Comment by andrnj** [comment]
We've identified the last affected accounts that contain previously configured routes with bad targets. We are contacting each affected customer directly with next steps. We will roll out the final fix after feedback from our affected customers.

**Comment by JayntiRaj** [comment]
We have contacted the affected customers about this issue and rolled out the fix for the edge case mentioned above.
