### ISSUE TITLE
Bug: Unable to create identically named resources within mesh using CloudFormation.

### ISSUE THREAD

**Issue by AKBarcenas** [aws/aws-app-mesh-roadmap#106]
**Summary**
What are you observing that doesn't seem right?
Using CloudFormation to create identically named virtual nodes under two different meshes will result in one of the virtual nodes failing to create. The error reported back states that a resource with the specified name already exists. This occurs for all resource types (VirtualNode, VirtualService, etc.) that are contained within a mesh. 

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?
1. Use the template below in CloudFormation.
```
---
Parameters:
  ServicesDomain:
    Type: String
    Default: "default.svc.cluster.local"
    Description: DNS namespace used by services e.g. default.svc.cluster.local

  AppMeshMeshName:
    Type: String
    Description: Name of mesh

  AppMeshMeshName1:
    Type: String
    Description: Name of mesh

  AppMeshVirtualNodeName:
    Type: String
    Description: Name of virtual node

Resources:
  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Ref AppMeshMeshName

  VirtualNode:
    Type: AWS::AppMesh::VirtualNode
    DependsOn: Mesh
    Properties:
      MeshName: !Ref AppMeshMeshName
      VirtualNodeName: !Ref AppMeshVirtualNodeName
      Spec:
        Listeners:
          - PortMapping:
              Port: 9080
              Protocol: http
        ServiceDiscovery:
          DNS:
            Hostname: !Sub "virtual-node.${ServicesDomain}"

  Mesh1:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Ref AppMeshMeshName1

  VirtualNode1:
    Type: AWS::AppMesh::VirtualNode
    DependsOn: Mesh1
    Properties:
      MeshName: !Ref AppMeshMeshName1
      VirtualNodeName: !Ref AppMeshVirtualNodeName
      Spec:
        Listeners:
          - PortMapping:
              Port: 9080
              Protocol: http
        ServiceDiscovery:
          DNS:
            Hostname: !Sub "virtual-node.${ServicesDomain}"
```

2. Enter two unique mesh names and virtual node name as parameters.
3. Create the stack.

**Are you currently working around this issue?**
How are you currently solving this problem?
This issue can be worked around by either giving the resources unique names when creating resources with CloudFormation or using CloudFormation alternatives such as the console or CLI to create identically named resources.

**Additional context**
Anything else we should know?
This only occurs then the identically named resources are of the same type. For example, there is no issue when creating a virtual node and virtual service with the same name.

This issue occurs regardless of whether or not the identically name resources are being created in the same stack or separate stacks.

**Comment by bcelenza** [comment]
This bug has been resolved in all regions.
