### ISSUE TITLE
Bug: :scheme header match is not being routed to

### ISSUE THREAD

**Issue by skiyani** [aws/aws-app-mesh-roadmap#116]
**Summary**
Currently header based routing for the pseudo header :scheme is not working. 

**Steps to Reproduce**
Run the http header walkthrough. Once everything is deployed the following command should route to yellow. The endpoint comes from the walkthrough's deployment script output:

```
curl -H "color_header: somestring" <endpoint>
```

Update ColorRouteYellow to include the Invert flag and set it to true. Update ColorRouteWhite to match on something other than GET. Redeploy the script. Now the same curl command above should route to ColorRouteBlack which is routing based on matching the scheme pseudo header to _http_

Expected behavior is to route to black but no routes will match this request.

**Comment by abaptiste** [comment]
Changing the scheme for the black node to `NONE` appears to work as expected.
Changing the scheme to any other value (originally `HTTPS` which wouldn't have worked, but using `HTTP` now) changes the behavior:

```
[ec2-user@ip-10-0-20-43 ~]$ curl -H "color_header: somestring" $ENDPOINT
black
[ec2-user@ip-10-0-20-43 ~]$ curl -H "color_header: somestring" $ENDPOINT
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 404</p>
        <p>Message: Not Found.</p>
        <p>Error code explanation: 404 - Nothing matches the given URI.</p>
    </body>
</html>
```

**Comment by abaptiste** [comment]
The ":scheme" pseudo-header is present only for ingress HTTP/2 requests and is provided by the underlying HTTP parsing library.

```
[2019-10-10 20:58:38.712][60][debug][http] [source/common/http/conn_manager_impl.cc:660] [C0][S4346809302262851359] request headers complete (end_stream=true):
':method', 'GET'
':path', '/'
':scheme', 'http'
':authority', 'localhost:10000'
'user-agent', 'curl/7.54.0'
'accept', '*/*'
```
We have a few options:
1. Modify Envoy to provide this pseudo header when parsing HTTP/1
2. Enforce Scheme filtering only for HTTP/2 requests.
3. Remove Scheme filtering.

**Comment by lavignes** [comment]
I'm not entirely against deprecating support for `:scheme` matching on routes due to the fact that it requires apps themselves to know about the egress TLS settings on their respective virtual nodes. 

Technically, since we do not support HTTP/2 outside of the Preview Channel, it shouldn't really cause any additional harm to deprecate the option (as it doesn't work on HTTP1 routes anyway).

**Comment by rajal-amzn** [comment]
We are currently investigating the options on how to handle the scheme header matches for HTTP routes. We will update this thread in the coming weeks.

**Comment by rajal-amzn** [comment]
We are deploying a change to prevent customers from defining match on `scheme` for `HTTP` routes till it is being fixed from Envoy. We have also reached out to existing customers who have `scheme` matching defined in their routes.

**Comment by rajal-amzn** [comment]
Changes to prevent new customers from defining `scheme` match for `HTTP` routes is deployed to all regions. All existing customers are made aware of this issue. Resolving this.
