### ISSUE TITLE
Support Envoy version 1.11.2

### ISSUE THREAD

**Issue by lavignes** [aws/aws-app-mesh-roadmap#118]
Envoy has recently announced a security release for Envoy as version 1.11.2. App Mesh should support this version and provide an updated Docker image.

You can read more about the CVEs resolved in 1.11.2 [here](https://groups.google.com/forum/#!topic/envoy-announce/Zo3ZEFuPWec).

**Comment by lavignes** [comment]
The managed image for App Mesh is now available as `840364872350.dkr.ecr.eu-west-3.amazonaws.com/aws-appmesh-envoy:v1.11.2.0-prod`

Documentation and examples will be updated throughout the day to reflect the latest version.

**Comment by dastbe** [comment]
Nice splits.! Is this WR?

**Comment by bcelenza** [comment]
Important note (wasn't obvious to me at first): The account ID is different from all previous Envoy release from App Mesh. This is intentional and will be the account ID used for all future releases.

**Comment by lavignes** [comment]
Just updating the status here. Most documentation/examples should be updated now. We're still working on getting the ECS console updated to the latest version of the image.
