### ISSUE TITLE
VPC Endpoint/Private Link for App Mesh Envoy xDS API

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-app-mesh-roadmap#12]
It would be great not to have to setup an IGW, NATGW or HTTP proxy for communication between Envoy sidecars and the App Mesh xDS API (e.g. `appmesh-envoy-management.us-east-1.amazonaws.com`, see [here](https://github.com/awslabs/aws-app-mesh-examples/issues/88#issuecomment-460491457)).

**Comment by dastbe** [comment]
Hey @ewbankkit (and everyone else!)

This feature was launched last week in all of our regions, you can see [our documentation](https://docs.aws.amazon.com/app-mesh/latest/userguide/vpc-endpoints.html) for more details.
