### ISSUE TITLE
Configurable IPv4/v6 preference on DNS Service Discovery

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#121]
**Tell us about your request**

I would like to define my DNS resolution preference s.t. I only get IPv4 or IPv6 responses

**Which integration(s) is this request for?**
All

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Today, App Mesh doesn't configure [dns lookup family](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#envoy-api-enum-cluster-dnslookupfamily) on clusters vended. This has the result of preferring IPv6 addresses over IPv4. 

This causes issue with external services that vend AAAA records, as the interactions w/ VPC routing and IPv6 are [difficult to reason about](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html)

**Are you currently working around this issue?**
Dealing with it.

**Additional context**
None

**Attachments**
None

**Comment by kiranmeduri** [comment]
At minimum this requires documentation update to highlight IPv6 is not handled appropriately in the context of App Mesh. Additionally a troubleshooting guide will help in identifying common errors in Envoy logs.

Proposal should also include Cloud Map as it supports IPv6 addresses already.

**Comment by bcelenza** [comment]
As noted in [this comment](https://github.com/aws/aws-app-mesh-roadmap/issues/2#issuecomment-662246849) on #2, Envoy's preferential usage of ipv6 is continuing to cause issues for communication with external services.

**Comment by efe-selcuk** [comment]
An additional note here in that it's not just a preference problem, but the VPC and ECS configuration may also be blocking IPv6 entirely. E.g., you'd need dual-stack ECS tasks for envoy to communicate with the external endpoint.

**Comment by saleem-mirza** [comment]
Is there any movement on this issue?

**Comment by acdha** [comment]
This a fairly big barrier to adopting egress filtering: many external services, including most CDNs, advertise IPv6 records and since this is outside of your control it's non-trivial to work around that.

**Comment by AKBarcenas** [comment]
IPv6 support has been released in App Mesh (https://github.com/aws/aws-app-mesh-roadmap/issues/314) and as part of this release we have allowed for Envoy's DNS resolver to be configured via a new field exposed on DNS service discovery.
