### ISSUE TITLE
Feature Request: sidecar injection

### ISSUE THREAD

**Issue by omerlh** [aws/aws-app-mesh-roadmap#126]
**Tell us about your request**
Automatically inject the required sidecar and init container to pods using a mutation webhook.

**Which integration(s) is this request for?**
EKS/Kubernetes

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today, to use AppMesh, we need to manually add the relevant containers. This is cumbersome and make it harder to adopt it. Also, every version update is more complex.

**Are you currently working around this issue?**
Manually adding the relevant containers.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by jaypipes** [comment]
@omerlh is this what you're looking for?

https://github.com/aws/aws-app-mesh-inject

**Comment by omerlh** [comment]
Yes, thanks!
