### ISSUE TITLE
Feature Request: OpenTracing/Prometheus support

### ISSUE THREAD

**Issue by omerlh** [aws/aws-app-mesh-roadmap#127]
**Tell us about your request**
Expose traffic metrics using OpenTracing (Jaeger/Zipkin) format or as Prometheus metrics

**Which integration(s) is this request for?**
All

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Today traffic metrics are reported only to AWS specific tools like CloudWatch/X-Rays. Supporting OpenTracing/Prometheus will allow customers to use existing open-source tools instead.

**Are you currently working around this issue?**
Using cloudwatch/X-Rays

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by stefanprodan** [comment]
Both Prometheus and Jaeger are supported, see https://github.com/aws/eks-charts#app-mesh-add-ons

**Comment by omerlh** [comment]
Ohh I see - thanks! Is there another place to learn more about AWS AppMesh? Both this and the injector (and also the CRD controller) is not in the official docs - unless I've missed something...

**Comment by stefanprodan** [comment]
I think you should close this issue and create another one with "Helm charts official docs".

**Comment by omerlh** [comment]
Sure. Will do!
