### ISSUE TITLE
Feature Request: native support for Hashicorp Consul & Nomad 

### ISSUE THREAD

**Issue by shuoyenl** [aws/aws-app-mesh-roadmap#135]
**Tell us about your request**
Native support of AWS app mesh for Hashicorp consul and nomad.

**Which integration(s) is this request for?**
Hashicorp Consul & Nomad 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We want to use AWS app mesh to enable the service mesh for our platform managed by Hashicorp stack.  AWS app mesh however does not currently provide a native support for consul/nomad. 

**Are you currently working around this issue?**
We may consider other solutions, e.g. Consul Connect, etc or will need to come up with our tool sets for managing app mesh resources.

**Additional context**
AWS app mesh provides native support for ecs, eks, and k8s but is currently difficult to be integrated with other cases. In order to make use of AWS app mesh for clusters managed by hashicorp consul/nomad, it requires tool sets to manage app mesh resources, inject sidecars, sync service records between consul and cloud map, etc.

**Comment by efe-selcuk** [comment]
Thanks for the feature request. We don't have any near-term plans for this but I've passed it onto our PM. This is interesting though. I'm not familiar with Consul and Nomad, just cursory reading now on their website.

If you have any additional information on how you'd expect this integration to look, what use cases you have that you'd want to replicate, etc., let us know.

**Comment by jtoberon** [comment]
To clarify one thing, App Mesh and Consul do work together today, e.g. see https://www.hashicorp.com/blog/enabling-service-discovery-consul-cloud-map/.

We do not have built in support for Nomad yet though.

**Comment by herrhound** [comment]
Resolving this issues as at the moment we don't have plans to support Nomad.
