### ISSUE TITLE
Feature Request: Support Linkerd as Proxy

### ISSUE THREAD

**Issue by virgofx** [aws/aws-app-mesh-roadmap#136]
**Tell us about your request**
Although Envoy is the current most popular proxy, Linkerd 2.x has been gaining traction and has better performance and memory usage (especially at high RPS when compared to Envoy). It would be nice it App Mesh could utilize either Envoy or Linkerd-proxy.

**Which integration(s) is this request for?**
EKS/Kubernetes

**Are you currently working around this issue?**
Not currently. Envoy is good; however, for large high-throughput meshes the latency of Envoy and for those that want the mesh to be based on linkerd-proxy this could be a deal-breaker.

**Comment by efe-selcuk** [comment]
Thanks for the feature request, this is certainly interesting. We won't have any near-term plans to support proxies other than Envoy, but I've passed this onto our PM. 

Any additional information you have on your setup, what you're trying to accomplish, and why Envoy doesn't fit the bill, will help.

**Comment by kiranmeduri** [comment]
@virgofx if possible can you share more details on the throughput numbers and latency differences between Envoy and Linkerd-proxy along with the use-cases you are using. For e.g. are the services plain-old HTTP(S) or gRPC/H2/something else.

**Comment by virgofx** [comment]
Currently using H2 . Nothing special; however, would prefer to run linkerd2-proxy opposed to envoy. There's a couple good blog posts that have extensive testing / benchmarks that can shed insight into throughput numbers. My use case really is just large clusters / meshes and the size of the memory footprint of the docker container impacts resources significant since it's sidecar'd in so many pods.

**Comment by wmorgan** [comment]
@virgofx any reason not to just use Linkerd directly, if you're on EKS?

**Comment by virgofx** [comment]
I have a few use cases in the AWS ecosystem where I'd like to move forward with App Mesh ... it's really just the proxy component would like to swap out Envoy with linkerd-proxy. The docs/user-guide are 100% envoy. I have some manual K8S and also EKS as well and while I can go full Linkerd directly, it somewhat defeats the purpose exploring some other integrations with AWS and service mesh.  

So the request really is just to allow adding the proxy component to be somewhat "modular" -- either envoy or linkerd-proxy ... if something else major comes along ... then supporting that too. And by supporting .... really just mostly documentation (not sure how much else is involved other then some basic configuration) in regards to configuration / endpoints / logging / etc.

**Comment by herrhound** [comment]
Resolving the issue, as we don't have plans to support linkerd-proxy. Please feel free to reopen it if you have additional input.
