### ISSUE TITLE
Cookie based routing

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#14]

**Comment by alvarow** [comment]
This will allow me to switch from my HAProxy homegrown solution to AppMesh

**Comment by shubharao** [comment]
You can use cookie values in routing using the header based routing which is launched in our Preview Channel. Check it out and let us know what you think! https://github.com/aws/aws-app-mesh-examples/tree/master/blogs/http-headers-and-priority

**Comment by lavignes** [comment]
I think we can moved this to done for now. Today you can match cookies by matching the Cookie header using regex.

For example, if you wanted to match http requests that had a cookie named `my_cookie`, you could write:

```json
{
  "httpRoute": {
    "match": {
      "headers": {
        "name": "cookie",
        "match": {
          "regex": "my_cookie=[^;]*"
        }
      }
    }
  }
}
```

We can certainly revisit this to improve the ergonomics of it a bit. Please feel free to chime in on this issue if you'd like to see us iterate on this.
