### ISSUE TITLE
HTTP Header based routing

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#15]

**Comment by stevensu1977** [comment]
there have any update about this feature ?

**Comment by bcelenza** [comment]
@stevensu1977 We've started working on this feature and will have an update here soon. :)

**Comment by atali** [comment]
Will you support JWT extracted from header to route.
We want to decode the JWT and extract for example a custom attribute and route the traffic based on that custom attribute.

**Comment by efe-selcuk** [comment]
This feature is available in our Preview Channel. Check it out and let us know what you think! https://github.com/aws/aws-app-mesh-examples/tree/master/blogs/http-headers-and-priority
