### ISSUE TITLE
Bug: CloudMap deregistration delay

### ISSUE THREAD

**Issue by bayarmunkh** [aws/aws-app-mesh-roadmap#151]
**Summary**
This is more of a question than a bug report.

Deploying a service cause intermittent DNS issue that results the old IP(s) still being referenced in other services, which causes a 503 error.

I wouldn't necessarily say this issue is 100% related to App Mesh. I think the underlying issue is https://github.com/aws/containers-roadmap/issues/343.

But this sounds like an issue that everyone uses AppMesh would run into. Is there a known workaround for this?

**Steps to Reproduce**
1. Create and deploy two services where one makes requests to the other.
2. Redeploy the receiving service while the call service has live traffic.
3. There is a brief period of 20-30 sec that the caller service still has a reference of the old IP(s) of the receiving service. That results 503 errors.

**Are you currently working around this issue?**
Tried setting the TTL to a lower value, and configuring a retry policy in the virtual routes. No luck.

**Additional context**
The env is ECS/Fargate, CloudMap, and App Mesh.

**Attachments**

**Comment by efe-selcuk** [comment]
Hey there. There is the DNS issue that you've linked to, though between retries and envoy's own health mechanisms I'd expect this to be less of a problem.

Could you please provide both your mesh configuration as well as any information about the configuration of your ECS services and cloudmap namespaces? e.g. a cloudformation template, if you have one; Envoy image version. Whatever I can use to repro.

**Comment by bayarmunkh** [comment]
Here are `service-a.svc.test` and `service-b.svc.test` services where `service-a` makes requests to `service-b`. 

The below is a terraform definition of `service-a`. `service-b`'s definition is identical. I didn't include the configuration of the ECS services, but they're fairly similar to [app mesh example](https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/fargate)

```terraform
resource "aws_appmesh_virtual_node" "vnode" {
  name      = "service-a-vn"
  mesh_name = "${var.mesh_id}"

  spec {
    backend = [
      {
        virtual_service {
          virtual_service_name = "service-b.svc.test"
        }
      }
    ]

    listener {
      port_mapping {
        port     = "8000"
        protocol = "http"
      }

      health_check {
        protocol            = "http"
        path                = "/health"
        healthy_threshold   = 5
        unhealthy_threshold = 5
        timeout_millis      = 2000
        interval_millis     = 5000
      }
    }

    service_discovery {
      aws_cloud_map {
        service_name   = "service-a.svc"
        namespace_name = "test"
      }
    }

    logging {
      access_log {
        file {
          path = "/dev/stdout"
        }
      }
    }
  }
}

resource "aws_appmesh_virtual_router" "vrouter" {
  name      = "service-a-vr"
  mesh_name = "${var.mesh_id}"

  spec {
    listener {
      port_mapping {
        port     = "8000"
        protocol = "http"
      }
    }
  }
}

resource "aws_appmesh_virtual_service" "vservice" {
  name      = "service-a.svc.test"
  mesh_name = "${var.mesh_id}"

  spec {
    provider {
      virtual_router {
        virtual_router_name = "${aws_appmesh_virtual_router.vrouter.name}"
      }
    }
  }
}

resource "aws_appmesh_route" "route" {
  name                = "service-a-route"
  mesh_name           = "${var.mesh_id}"
  virtual_router_name = "${aws_appmesh_virtual_router.vrouter.name}"

  spec {
    http_route {
      match {
        prefix = "/"
      }

      action {
        weighted_target {
          virtual_node = "${aws_appmesh_virtual_node.vnode.name}"
          weight       = 100
        }
      }
    }
  }
}

resource "aws_service_discovery_service" "service_discovery" {
  name = "service-a.svc"

  dns_config {
    namespace_id = "${var.namespace_id}"

    dns_records {
      ttl  = 10
      type = "A"
    }

    routing_policy = "MULTIVALUE"
  }

  health_check_custom_config {
    failure_threshold = 1
  }
}
```

>  Envoy image version

Tried both `1.12.1.0-prod` and `1.12.2.1-prod`. Same result.

> Are you using CloudMap DNS or are you using the integrated CloudMap endpoints?

the integrated CloudMap endpoints

> Have you configured retries on your request routes?

You don't see the retry config in the above TF definition. But I've tried {Error: gateway-error, Timeout: 2s, Max Retries: 3} retry config.

The combination of lower TTL in Cloud Map and a retry on gateway-error in App Mesh lowers the number of failures but the issue doesn't go away completely.

**Comment by jtoberon** [comment]
We will publish recommended ECS/k8s, App Mesh, and application settings to reduce HTTP 503 errors. In our testing, we found these to be a great mitigation handling the unexpected loss of an ECS task / k8s pod.

While we continue to work with the ECS and Cloud Map teams to reduce propagation delays across systems, these settings will help make sure that planned changes (e.g. a deployment, scaling in capacity, or scaling out an application that has a very long startup time) don't result in HTTP 503s.

**Comment by bayarmunkh** [comment]
@dastbe does that mean https://github.com/aws/containers-roadmap/issues/343 is fixed?

**Comment by dastbe** [comment]
Reading through the linked issue, that bug is related to not respecting TTLs. The bug we fixed in ECS was an ordering issue where some tasks may be stopped before new tasks are actively visible in DNS. I believe they are also looking into the deregistration issue as well.

On TTLs, Envoy doesn't actually respect DNS TTLs by default, and will query for dns updates every ~5s in success or failure. Now, between Envoy and the actually authority could be a variety of caching resolvers that could be causing the latency issue. We're also aware that by default CloudMap sets a 900s min TTL for NXDOMAIN, which means if you make a query for a service and it isn't present then you can be guaranteed minutes of empty responses from caches. We recommend generally setting very low TTLs, and we're working on making that an option for SOA records in CloudMap as well. We also recommend using our direct CloudMap integration as that avoids the potential for intermediate caching issues. Since we know what our consumers are, we can be much more intelligent about when we query CloudMap and when we distribute changes down to Envoys.

Additionally, we're working on making the configuration vended to Envoy more resilient overall to these kinds of failures, so that temporary proxy issues don't result in application failures.

**Comment by awsiv** [comment]
Would be really good to have this integrated with envoy connection draining: https://github.com/aws/aws-app-mesh-roadmap/issues/252

**Comment by ldecaro** [comment]
I see this is just shipped. Is this fix only in the context of AppMesh or also ECS?
