### ISSUE TITLE
Service to service communication using App Mesh

### ISSUE THREAD

**Issue by fitzplb** [aws/aws-app-mesh-roadmap#152]
I actually don't think this is a bug but my previous experience of AWS support when I have logged a question relating to App Mesh issues is poor and the last time I posted a question about App Mesh configuration on the forums I was advised to post here as this is monitored more closely.

I have a number of ECS Fargate services that are enabled for App Mesh. These services are currently accessed through ALB and when services communicate with each other they use the public DNS name to communicate. We are now trying to switch these services to use the service mesh to communicate. 

For example we have a service called **dev-scim-service-Service-1NMGNBMOCQDC** which communicates with **dev-user-service-Service-13JCWJXHRMBI5**. We pass an environment variable into the container for the scim-service called USER_SERVICE_URL which is set to `https://dev-user-service.mydomain.com`. This is the public DNS name and resolves to the ALB. Communication is working when this URL is used.

We are now trying to use the service discovery name for the user-service by setting USER_SERVICE_URL to `http://user-service.my-stack-prefix-ecsservicesdomain` which is also the name of the virtual service I have configured for the user-service. The virtual node for the scim-service has been configured with the virtual service for the user-service as a backend. From the envoy logs it appears that service discovery via DNS is working as when we make a call to the scim-service that requires it to make an upstream request to the user-service the following is logged:

`GET /user?query=%7B%0A%20%20%20%20%20%20user%20(id%3A%20%225de79992c655ee698e2f74e9%22)%20%7B%0A%20%20id%0A%20%20email%0A%20%20firstName%0A%20%20lastName%0A%20%20status%0A%20%20ref%0A%20%20createdAt%0A%20%20updatedAt%0A%20%20status%0A%20%20positions%20%7B%0A%20%20%20%20id%0A%20%20%20%20manager%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20ouId%0A%20%20%20%20title%0A%20%20%20%20startDate%0A%20%20%20%20isActive%0A%20%20%7D%0A%7D%0A%20%20%20%7D HTTP/1.1" 503 UF 0 91 1035 - "-" "axios/0.19.0" "8c6b3cc8-e529-9819-afc9-7e5c51048c54" "user-service.my-stack-prefix-ecsservicesdomain" "10.181.32.93:80`

It looks to me like the service discovery aspect is working as the IP address in the envoy log matches the IP address for the user-service in the `my-stack-prefix-ecsservicesdomain` zone in Route 53 (and in the ECS console). However the http response code is 503 and nothing is returned so I suspect my configuration is wrong. 

I've attached some files showing the configuration of the ECS and AppMesh resources for both services. I'm hoping this provides enough information for someone more knowledgeable to spot what I'm doing wrong!

[ecs2.txt](https://github.com/aws/aws-app-mesh-roadmap/files/4076326/ecs2.txt)
[appmesh2.txt](https://github.com/aws/aws-app-mesh-roadmap/files/4076327/appmesh2.txt)

**Comment by lavignes** [comment]
One thing I immediately notice is that you have your mesh egress filter set to `ALLOW_ALL`. Not that this causes your specific problem but I can mask issues since this actually allows the your applications to bypass the Envoy proxy to make requests if they cannot find an appropriate route to an upstream host.

Especially if you're just testing out your config it could help to keep that turned off unless you actually need it.

https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_EgressFilter.html

**Comment by bcelenza** [comment]
>  this actually allows the your applications to bypass the Envoy proxy to make requests if they cannot find an appropriate route to an upstream host

A (very) minor clarification on this statement: Envoy is still proxying the traffic when egress filter is set to `ALLOW_ALL`, but the traffic could end up being proxied as pure TCP instead of HTTP (depending on how the traffic is matched by our rules). 

That said, modelled config (i.e. backends) should take precedence, so only disable this if it really isn't needed, as @lavignes mentions.

Glancing at the mesh config, I don't see anything that stands out as problematic. A few other things that would help:

1. A [config dump](https://www.envoyproxy.io/docs/envoy/latest/api-v2/admin/v2alpha/config_dump.proto) from both the envoy that's sending the request, and the envoy that's receiving it.
2. Envoy logs (preferably DEBUG level) from both Envoys

And just to rule out anything on our side: the region in which you tested this.

**Comment by fitzplb** [comment]
The egress filter is set to `ALLOW_ALL` because the containers we run need to connect to an external MongoDB cluster and whilst I tried modelling each MongoDB cluster node as a virtual service in AppMesh I couldn't get it working. I had a ticket open with AWS support for about 3 months on that one but we never got to the bottom of it and in the end I gave up and set the filter to `ALLOW_ALL` on the basis that I could always come back at some point and block unwanted external traffic with security group rules. I've just tried it with `DENY_ALL` in case it is masking something but the behaviour appears the same.

I've attached debug logs for both envoys. I'm not sure how to get the config dump when it's running on Fargate, can you give me any pointers?

The region is eu-west-2.

[scim-envoy.log](https://github.com/aws/aws-app-mesh-roadmap/files/4085877/scim-envoy.log)
[user-envoy.log](https://github.com/aws/aws-app-mesh-roadmap/files/4085878/user-envoy.log)

**Comment by dastbe** [comment]
Looking at your access logs it does appear that your scim envoy is making an outbound request to the user envoy, correlating on the ip address `10.181.35.186`. However, from those logs it does not appear to be the case that traffic is making it from your downstream envoy to the upstream.

Taking a step back, what are the security groups for your ecs tasks? are they both in the same VPC?

Additionally, if you could provide the Virtual Node, Virtual Service, Virtual Router, route configuration between these two envoys that would be helpful.

**Comment by fitzplb** [comment]
```
VPC     
vpc-0bc43274e85134c2b

Subnets         
subnet-07c9da0034698bf2b
subnet-0779ddedd48a6cc29

Security Groups
sg-023f43ddffa02fb2c

SG rules
Description Access to the ECS hosts and the tasks/containers that run on them
Ingress
protocol        port range      source  description
ALL             sg-07e5fd49863db5b60   
ALL             sg-0ffd079733ebd5e6d    Prometheus monitoring
Egress
protocol        port range      destination     description
ALL             0.0.0.0/0       

Subnets routing :

subnet-0779ddedd48a6cc29

Route Table: rtb-0cb88b17416de8767
Destination     Gateway Status
192.168.240.0/21        pcx-0b6d496546be50b7e   active
10.181.0.0/16   local   active
0.0.0.0/0       nat-031b2d47ad242387c   active
pl-7ca54015     vpce-011cbeeaf7289c74c  active


subnet-07c9da0034698bf2b

Route Table: rtb-074964752a82b05d2
Destination     Gateway Status
192.168.240.0/21        pcx-0b6d496546be50b7e   active
10.181.0.0/16   local   active
0.0.0.0/0       nat-006ee83588fcb5b19   active
pl-7ca54015     vpce-011cbeeaf7289c74c  active
```

The virtual node, service, router and route configuration is in my first post in the appmesh2.txt attachment.

**Comment by fitzplb** [comment]
Support have pointed out that the security group doesn't allow the ECS tasks to communicate with each other! Just needed another ingress rule. Thanks for looking folks.
