### ISSUE TITLE
Feature Request: Jaeger support with ECS

### ISSUE THREAD

**Issue by dgalichet** [aws/aws-app-mesh-roadmap#155]
**Tell us about your request**
Actually it seems that envoy can be configured with XRay tracing support but doesn't Jaeger

**Which integration(s) is this request for?**
ECS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
AppMesh/ECS supports XRay but we prefer to rely on an solution like jaeger that supports standard opentracing/opentelemetry. As there is an impact on applications code, we prefer to rely on a widely supported standard

**Are you currently working around this issue?**
either not using tracing, or modifying AWS envoy container image. These two solutions are not really relevant.

**Additional context**
I've seen an initiative to use opentelemetry in XRay (https://github.com/awslabs/aws-xray-sdk-with-opentelemetry) but it seems it will not be available/usable in a near future

**Comment by dastbe** [comment]
Hey @dgalichet 

Not sure if `modifying AWS envoy container image` includes adding files to the image, but you can make this work via the following

* Adding a file at a well-known location (ex. `/tmp/envoy-tracing-cfg.yaml`) to your base image with your tracing config. For example, I've highlighted the config for jaeger via zipkin [here](https://github.com/envoyproxy/envoy/blob/ac88316892cd47b6a9b58e3736e20e8863cd0d27//examples/jaeger-tracing/front-envoy-jaeger.yaml#L48-L69). Note you'll need to ensure the jaeger cluster is parented under `static-resources > clusters`
* Set the environment variable `$ENVOY_TRACING_CFG_FILE` to the file location within your image.

We can look at adding support for more easily configuring jaeger and other tracing options directly, but this is (IMO) the most flexible mechanism for doing so as you don't have to rely on us to pipe higher level configuration flags through as arguments.

**Comment by dgalichet** [comment]
Hi @dastbe 

thanks a lot for the answer, It makes perfect sense to me. I will probably add configuration in a side car container and mount it on envoy container (and specify the environment property that I didn't know was existing).
I can close this issue and will open a new one if I encounter some troubles.
