### ISSUE TITLE
Feature Request: Release App Mesh vended Envoy v1.13.0 image

### ISSUE THREAD

**Issue by lavignes** [aws/aws-app-mesh-roadmap#156]
**Tell us about your request**
The Envoy team has just released v1.13.0:

https://www.envoyproxy.io/docs/envoy/v1.13.0/intro/version_history

**Comment by hugoprudente** [comment]
#168 is related to the same issue.

**Comment by dastbe** [comment]
As was mentioned on another issue, we prioritized improving our Envoy qualification process ahead of releasing new minor versions of Envoy. Now that is completed, we have released a 1.15 Envoy image and have no plans to backfill older Envoy releases from 1.13 or 1.14
