### ISSUE TITLE
Bug: Error when using App Mesh with EKS on Fargate

### ISSUE THREAD

**Issue by shubharao** [aws/aws-app-mesh-roadmap#158]
(Customer reported on Twitter: Idan Frimark @FrimarkIdan)

**Summary**
What are you observing that doesn't seem right?
Hi, Is there any tutorial how to use AppMesh with EKS Fargate? I've tried https://docs.aws.amazon.com/eks/latest/userguide/mesh-k8s-integration.html but failed due to "Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: NET_ADMIN"

**Comment by shubharao** [comment]
Update - The team is working on cutting a new release of app-mesh-inject-controller in the next couple days. More details are here: https://github.com/aws/aws-app-mesh-examples/pull/241#issuecomment-576779280

**Comment by kiranmeduri** [comment]
Update - aws-app-mesh-inject is updated to version 0.4.0, helm charts are also updated https://github.com/aws/eks-charts/commit/d7bc97988d1bac377e5fe6d83ac22a3aa510a5d1
