### ISSUE TITLE
Bug: IAM Roles for Service Accounts fails w/o error message when Envoy doesn't have read permissions

### ISSUE THREAD

**Issue by M00nF1sh** [aws/aws-app-mesh-roadmap#159]
**Summary**
Envoy on EKS Fargate don't work, i tried both 1.12.2.1-prod and v1.12.1.1-prod with iam-for-pods.

Logs from envoy pod:
```
[2020-01-23 03:04:40.815][1][debug][config] [bazel-out/k8-fastbuild/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:47] Establishing new gRPC bidi stream for rpc StreamAggregatedResources(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);

[2020-01-23 03:04:40.815][13][debug][aws] [source/extensions/filters/http/common/aws/credentials_provider_impl.cc:52] Getting AWS credentials from the environment
[2020-01-23 03:04:40.815][13][debug][aws] [source/extensions/filters/http/common/aws/credentials_provider_impl.cc:201] Getting AWS web identity credentials from STS: sts.us-east-1.amazonaws.com
[2020-01-23 03:04:40.816][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:201] notifyRemoteClose 13
[2020-01-23 03:04:40.816][1][warning][config] [bazel-out/k8-fastbuild/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13,
[2020-01-23 03:04:40.816][1][debug][config] [source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.Listener failed
[2020-01-23 03:04:40.816][1][debug][config] [source/common/config/grpc_mux_subscription_impl.cc:70] gRPC update for type.googleapis.com/envoy.api.v2.Cluster failed
[2020-01-23 03:04:40.816][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:221] resetStream
[2020-01-23 03:04:40.816][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:378] Stream cleanup with 0 in-flight tags
[2020-01-23 03:04:40.816][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:367] Deferred delete
[2020-01-23 03:04:40.816][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:144] GoogleAsyncStreamImpl destruct
```
```
 curl "http://localhost:9901/stats"
cluster_manager.active_clusters: 0
cluster_manager.cds.init_fetch_timeout: 0
cluster_manager.cds.update_attempt: 48
cluster_manager.cds.update_failure: 47
```
```
COLORGATEWAY_SERVICE_PORT_HTTP=9080
COLORTELLER_BLACK_SERVICE_PORT_HTTP=9080
ENVOY_LOG_LEVEL=debug
AWS_ROLE_ARN=<role-with-admin-permission>
TCPECHO_PORT_2701_TCP_PORT=2701
HOSTNAME=colorgateway-676484bd55-zmcbr
COLORTELLER_BLACK_PORT_9080_TCP_PROTO=tcp
COLORGATEWAY_PORT_9080_TCP_PROTO=tcp
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
COLORGATEWAY_SERVICE_PORT=9080
COLORTELLER_BLACK_SERVICE_PORT=9080
TERM=xterm
COLORTELLER_SERVICE_HOST=10.100.182.144
KUBERNETES_PORT=tcp://10.100.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
TCPECHO_SERVICE_HOST=10.100.70.252
COLORTELLER_BLUE_PORT_9080_TCP_ADDR=10.100.86.78
COLORTELLER_BLUE_PORT_9080_TCP_PROTO=tcp
COLORTELLER_BLUE_PORT=tcp://10.100.86.78:9080
KUBERNETES_SERVICE_PORT=443
COLORTELLER_RED_PORT_9080_TCP_ADDR=10.100.127.235
COLORTELLER_RED_PORT=tcp://10.100.127.235:9080
KUBERNETES_SERVICE_HOST=10.100.0.1
TCPECHO_PORT_2701_TCP_ADDR=10.100.70.252
COLORTELLER_BLUE_SERVICE_HOST=10.100.86.78
COLORTELLER_RED_SERVICE_HOST=10.100.127.235
APPMESH_PREVIEW=0
COLORTELLER_PORT_9080_TCP_ADDR=10.100.182.144
COLORGATEWAY_PORT_9080_TCP_PORT=9080
COLORTELLER_BLACK_PORT_9080_TCP_PORT=9080
COLORTELLER_PORT=tcp://10.100.182.144:9080
APPMESH_VIRTUAL_NODE_NAME=mesh/color-mesh/virtualNode/colorgateway-demo
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
COLORTELLER_BLUE_PORT_9080_TCP=tcp://10.100.86.78:9080
COLORGATEWAY_PORT_9080_TCP=tcp://10.100.165.222:9080
COLORTELLER_BLACK_PORT_9080_TCP=tcp://10.100.13.165:9080
COLORTELLER_RED_PORT_9080_TCP_PORT=9080
PWD=/
COLORGATEWAY_SERVICE_HOST=10.100.165.222
COLORTELLER_BLACK_SERVICE_HOST=10.100.13.165
COLORTELLER_PORT_9080_TCP=tcp://10.100.182.144:9080
COLORTELLER_SERVICE_PORT_HTTP=9080
AWS_REGION=us-east-1
COLORTELLER_PORT_9080_TCP_PROTO=tcp
COLORTELLER_BLACK_PORT=tcp://10.100.13.165:9080
COLORTELLER_RED_SERVICE_PORT=9080
COLORGATEWAY_PORT=tcp://10.100.165.222:9080
TCPECHO_SERVICE_PORT=2701
TCPECHO_PORT_2701_TCP_PROTO=tcp
SHLVL=1
HOME=/
KUBERNETES_PORT_443_TCP_PROTO=tcp
COLORTELLER_PORT_9080_TCP_PORT=9080
KUBERNETES_SERVICE_PORT_HTTPS=443
COLORTELLER_RED_PORT_9080_TCP=tcp://10.100.127.235:9080
COLORTELLER_RED_SERVICE_PORT_HTTP=9080
TCPECHO_PORT=tcp://10.100.70.252:2701
COLORTELLER_BLUE_SERVICE_PORT_HTTP=9080
TCPECHO_PORT_2701_TCP=tcp://10.100.70.252:2701
COLORGATEWAY_PORT_9080_TCP_ADDR=10.100.165.222
COLORTELLER_BLACK_PORT_9080_TCP_ADDR=10.100.13.165
COLORTELLER_BLUE_PORT_9080_TCP_PORT=9080
COLORTELLER_RED_PORT_9080_TCP_PROTO=tcp
COLORTELLER_SERVICE_PORT=9080
KUBERNETES_PORT_443_TCP_ADDR=10.100.0.1
KUBERNETES_PORT_443_TCP=tcp://10.100.0.1:443
COLORTELLER_BLUE_SERVICE_PORT=9080
```
BTW, I'm running AppMesh controller & AppMesh injector(fixed the init container issue) on EC2 nodes to isolate the problem. Both of them works correctly, e.g. created correct AppMesh objects and injected envoy & iam-for-pod environment variables correctly.

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by kiranmeduri** [comment]
Checked with https://github.com/aws/aws-app-mesh-examples/pull/241 in us-east-2 that it works as expected. Trying to setup in us-east-1. 

```
kubectl exec -it -n howto-k8s-fargate $greenpod -c envoy curl http://localhost:9901/stats | grep cluster_manager.cds.update
cluster_manager.cds.update_attempt: 40
cluster_manager.cds.update_failure: 0
cluster_manager.cds.update_rejected: 0
cluster_manager.cds.update_success: 39
```

**Comment by kiranmeduri** [comment]
@M00nF1sh verified in us-east-1 that the example I have works. Certainly the number of steps required to get everything work is a lot. Below are some details to compare with your setup.

*pod*: [front.json.txt](https://github.com/aws/aws-app-mesh-roadmap/files/4101254/front.json.txt)

```
kubectl exec -it -n howto-k8s-fargate $greenpod -c envoy curl http://localhost:9901/stats | grep cluster_manager.cds.update
cluster_manager.cds.update_attempt: 20
cluster_manager.cds.update_failure: 0
cluster_manager.cds.update_rejected: 0
cluster_manager.cds.update_success: 19
```

**Comment by dastbe** [comment]
@M00nF1sh would be additional helpful to provide pod spec, network policies, &c

From our side once we understand why it's failing we need to improve debug output to properly explain the error.

I would also try re-running at ENVOY_LOG_LEVEL=trace and see if there's any additional information being emitted between the STS call and the internal error.

**Comment by M00nF1sh** [comment]
Thanks so much for the help.
I'm missing the ` fsGroup: 1337` setting, envoy containers is not running as root, thus it cannot read the credentials file without it , and resulted in the error. 👍  (But indeed the error message should be somehow improved since there is nothing in logs indicate that error)

**Comment by dastbe** [comment]
Reopening this issue. As part of the IAM work we need to improve the debugging story here.

**Comment by kiranmeduri** [comment]
Is there a way to hard fail Envoy on bootstrap? I am thinking if Envoy or wrapper script can verify that IAM credentials are good to go. May be a proper readinessprobe will work too. Any ideas?

**Comment by lavignes** [comment]
Health checks should fail if an Envoy doesn't get LDS/CDS resources. If we wanted to do something else I think we just need to be careful about the definition of "good to go". 

Say, if the entire set of credential providers is ran and we still don't have credentials we probably could instruct Envoy to shut down. But it still doesn't help inform a user of what they did wrong. We will add a log when we can't read the token file in Envoy 1.13.0 onwards, but I'm not sure about what else could be helpful.

**Comment by dastbe** [comment]
@lavignes can we emit a metric on credential retrieval failures?

As part of improved debugging logs, we can also start collating common failures for Envoy to connect and document remediation

**Comment by lavignes** [comment]
@dastbe yes. and we **should**. This has just been neglected.

**Comment by FrimIdan** [comment]
> I'm missing the ` fsGroup: 1337` setting
@M00nF1sh is this a setting that should be on every deployment in order that envoy will work? Why app-mesh-inject isn't in charge on adding it to the pod?

**Comment by kiranmeduri** [comment]
> > I'm missing the ` fsGroup: 1337` setting
> > @M00nF1sh is this a setting that should be on every deployment in order that envoy will work? Why app-mesh-inject isn't in charge on adding it to the pod?

It will be handled by aws-app-mesh-inject in upcoming release (0.4.0)

**Comment by M00nF1sh** [comment]
actually 0.5.0  or 0.4.1 :D

**Comment by jamsajones** [comment]
@M00nF1sh with the GA release of controller and injector, can this be closed?

**Comment by fawadkhaliq** [comment]
It can be closed. appmesh-controller v1.0.0+ has the changes [1] to handle this. It was added to appmesh-controller in this PR [2] and refactored/touched here [3]

[1] https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/inject/iam_for_service_accounts.go
[2] https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/166
[3] https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/196
