### ISSUE TITLE
Emit DogStatsD-compatible metrics

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#16]
App Mesh will allow customers to enable DogStatsD metrics to a local sidecar agent or remote agent.  The agent must be capable of ingesting DogStatsD metrics; examples include the CloudWatch agent and the DataDog agent.  The metrics will be tagged/dimensioned to allow for aggregating metrics across multiple endpoints as desired.

**Comment by jlambert121** [comment]
This was moved to "Just Shipped", but I'm not able to find specific documentation on how to configure this.  Would you be able to link to some documentation on how to send metrics to a remote Datadog agent?

**Comment by bcelenza** [comment]
Hey @jlambert121, have you looked at the [DogStatsD](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html) environment variables for the Envoy sidecar image? Hope that helps get you started.

**Comment by jlambert121** [comment]
> Hey @jlambert121, have you looked at the [DogStatsD environment variables](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html) for the Envoy sidecar image? Hope that helps get you started.

It does - thank you!  For future things, having that link added to this card when completing it would have let me know where to go find it!

**Comment by voxxit** [comment]
I still think this needs a bit more documentation. As of now, I am stuck trying to build our own Envoy image using `111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.9.1.0-prod` as a base image. This does not seem to be working.

Are there clearer instructions for when you do not have a discoverable DNS endpoint for Datadog, i.e. when you have it running on the host IP? We typically provide this via an environment variable, i.e. `DATADOG_HOST_IP`.

**Comment by lavignes** [comment]
@voxxit I can make an issue to add some clarifying documentation for this.
Just to make sure though. Are you setting the environment variable `ENVOY_STATS_SINKS_CFG_FILE` as in what is documented in: https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html#envoy-dogstatsd-config ?

You should be able to point that to a YAML file that looks like this:

```yaml
address:
  socket_address:
    protocol: udp
    address: 127.0.0.1
    port_value: 8125
```
