### ISSUE TITLE
Bug: Failed calls in CloudTrail only show "InternalFailure" Error

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#163]
**Summary**

When an App Mesh API call fails (for example, because of a NotFoundException), the associated CloudTrail event does not have the actual error, instead showing a generic "InternalFailure" code.

**Steps to Reproduce**

1. Make failing call. For example, `aws appmesh --debug describe-mesh --mesh-name i-never-created-this-mesh` probably fails for you. Record the request id
2. In CloudTrail, query for the event that corresponds to the above request id
3. Observe that the event has an error code of `InternalFailure`

**Are you currently working around this issue?**

Not a problem w/ App Mesh itself, but for audit purposes this makes failure events less useful.

**Additional context**

No

**Attachments**

None

**Comment by efe-selcuk** [comment]
This was resolved in Q3 2020.
