### ISSUE TITLE
Feature Request: Add additional fields to X-Ray tracing output

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#164]
**Tell us about your request**

We've heard at least one ask for additional data to be emitted in the x-ray traces. For example, adding sourceIp and destinationIp would help isolate traces down to a particular instance.

Opening this issue so that we can gather more feedback about what fields are pertinent to you, so we can understand what we need to develop to get that data injected.

**Which integration(s) is this request for?**

All

**Comment by nealp9084** [comment]
This PR added the Source IP address to the x-ray trace: https://github.com/envoyproxy/envoy/pull/10014. This will be available in the next AppMesh release of Envoy.

The Destination IP address should already be stored in the x-ray trace; it's supposed to be an [annotation](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-annotations) named `upstream_address`.
