### ISSUE TITLE
Bug: Routing by header rule not respected in virtual router

### ISSUE THREAD

**Issue by lewislabs** [aws/aws-app-mesh-roadmap#167]
**Summary**
We created two virtual nodes "serviceA" and "serviceA-v2" 
We created a virtual service named "serviceA"
We then setup a virtual router with the following rules
```
# RULE 1
- Path: "/" 
- Priority: 100
- Header match EXACT "branch" = "v2" 
- Target: "serviceA-v2"
```

```
# RULE 2
- Path: "/" 
- Priority: 1 
- Target: "serviceA"
```

Routing to service A always seems to round robin requests to the "serviceA" node, regardless of whether the "branch: v2" header is set or not. 

Looking through the documentation it wasn't particularly clear how this is actually supposed to work but based on intuition I would expect to be able to control the routing of a request to either the "serviceA" or "serviceA-v2" node just by supplying the http header or not. 

**Steps to Reproduce**

After deploying the above AppMesh setup. From inside a container deployed via ECS and part of the mesh, running `curl -H "branch: v2" http://serviceA.meshnamespace/" will return a result from "serviceA" and then subsequently from the "serviceA-v2" node. 

**Are you currently working around this issue?**
How are you currently solving this problem?

We're not. 

**Additional context**
If there is more documentation to help describe how to setup header based routing that would be helpful. 

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by lewislabs** [comment]
There's a chance #65 is related here. It's unclear how virtual service naming relates to how the service should be called via a DNS hostname resolution.

**Comment by dastbe** [comment]
Hey @lewislabs, 

Looking at the configuration you provided, you have rule 2 at priority 1 and rule 1 and priority 100. App Mesh has priorities sorted from smallest to largest (so priority 0 is highest), with equal/undefined priority having undefined ordering.

Additionally, routes are followed based on first match rather than best match. So what's happening for you here is that rule 2 is evaluated first, matching all traffic, and **only** routing to serviceA. If you flipped the priority of the two routes, you should be able to get the behavior you want.

**Comment by dastbe** [comment]
On

> It's unclear how virtual service naming relates to how the service should be called via a DNS hostname resolution.

You should query virtual services by their virtual service name. In the future, we may do further work to decouple virtual service names from the fqdn you need to use within your mesh as #65 discusses.

**Comment by lewislabs** [comment]
Thanks for the quick response @dastbe 

Looking back at this now I think I actually wrote the issue up incorrectly and we did have these priorities swapped. So RULE 1 was priority 1 and Rule 2 was priority 100. I'll re-test this to confirm 100%.

This still doesn't explain why our traffic was still going to "serviceA-v2" when there's no header set on the request though does it? Regardless of the priority, I would expect that with only these two rules in the router requests should stick to either serviceA or serviceA-v2, not round robin between them.

**Comment by dastbe** [comment]
Ah, I was a little confused as your first description was

> Routing to service A always seems to round robin requests to the "serviceA" node, regardless of whether the "branch: v2" header is set or not.

But seeing round robin behavior across serviceA and serviceA-v2 would not be expected from the above configuration. 

In addition to verifying your configuration for the service and router, could you also

* tell us how your service discovery is set up for the serviceA and serviceA-v2 nodes?

* whether you have the egress filter set to allow_all/deny_all in your mesh?

**Comment by lewislabs** [comment]
I will verify the configuration and let you @dastbe

**Comment by dastbe** [comment]
Hey @lewislabs any update?

**Comment by lewislabs** [comment]
Hi @dastbe. I'm trying to put together a full reproducible stack with the CDK to test this out and give something more tangible to work with and tweak.

**Comment by dastbe** [comment]
Hey @lewislabs, I'm going to close this issue out for now as we have an answer for the original description and the current thread has gone stale. Once you have a new setup please re-open and we can continue investigating. Thanks!
