### ISSUE TITLE
Support AWS X-Ray Tracing

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#17]
App Mesh will allow customers to enable X-Ray tracing on a per-mesh basis.  Once enabled, customers can view X-Ray segment data and configure sampling through the AWS X-Ray Console, API, or CLI.  If X-Ray Tracing is enabled, App Mesh will emit X-Ray tracing segments to the X-Ray agent, running either as a sidecar in the task/pod or running elsewhere in the customer's account.

**Comment by markhibberd** [comment]
Is it possible to set the x-ray host? This implies I should be able to run an agent that isn’t on 127.0.0.1 but documented configuration only exposes the port, so I can’t tell if this is actually supported.

**Comment by efe-selcuk** [comment]
@markhibberd Right now, it's hard-coded. #95 should address that. It'll allow more general configuration of the x-ray extension.
