### ISSUE TITLE
Bug: VirtualNode API accepts two backends with the same name

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-roadmap#170]
**Summary**

The API currently accepts multiple backends with the same virtual service name without returning a client error, but it coerces them down to a single backend. This was less of an issue when the backend struct only contained the service name, but now there's also client policies (#38) that make the backends more distinguishable.

API should validate this and return a client error, as I believe this is an invalid case in the current API.

**Steps to Reproduce**

Create a virtual node with two backends with the same virtual service name and inspect the response.

```
aws appmesh create-virtual-node --virtual-node-name bar --mesh-name foo --spec '{ "backends": [ {"virtualService": {"virtualServiceName" : "a"} }, {"virtualService": {"virtualServiceName": "a"}} ]}’

{
    "virtualNode": {
        "meshName": "foo",
...
            "backends": [
                {
                    "virtualService": {
                        "virtualServiceName": "a"
                    }
                },
                {
                    "virtualService": {
                        "virtualServiceName": "a"
                    }
                }
            ]
        },
...
    }
}
```

Then describe and see the single backend:

```
aws appmesh describe-virtual-node --mesh-name foo --virtual-node-name bar
{
    "virtualNode": {
...
        "spec": {
            "backends": [
                {
                    "virtualService": {
                        "virtualServiceName": "a"
                    }
                }
            ]
        },
...
    }
}
```

**Are you currently working around this issue?**

I don't think there's a workaround.

**Comment by JayntiRaj** [comment]
The fix for this bug had been deployed globally
