### ISSUE TITLE
Feature Request: The ability to delete a mesh, without deleting every individual component first

### ISSUE THREAD

**Issue by nbrandaleone** [aws/aws-app-mesh-roadmap#179]
**Tell us about your request**
What do you want us to build? Currently, in the Console one cannot delete a mesh, without deleting all individual components (virtual routers/routes, services, and nodes) first. Except for the smallest meshes, the number of individual components sky-rocket. Clicking through them all is tedious and difficult as some components have dependencies on other components which must therefore be deleted in a specific order.

When I delete the mesh, I want the entire mesh to be deleted with a single button press.  This is similar to the operation of deleting a namespace in kubernetes.  The namespaces, and all objects living within the namespace are deleted at once.  There is one need to track down individual objects.

**Which integration(s) is this request for?**
All AppMesh - Console experience only.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

I am trying to have a better user experience, when cleaning up resources.

**Are you currently working around this issue?**
How are you currently solving this problem?
I am scripting or using CF/CDK or scripts for creation/deletion.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by herrhound** [comment]
Resolving this feature request as we are not planning to implement it.
