### ISSUE TITLE
[Question] How to canary release the gateway?

### ISSUE THREAD

**Issue by hffmnn** [aws/aws-app-mesh-roadmap#183]
I am (still looking) at the [ECS walkthrough](https://github.com/aws/aws-app-mesh-examples/tree/master/examples/apps/colorapp) and I am wondering how to (or if it is possible at all) to canary release the gateway?

It looks like it is not possible to target a router directly via the ALB, so the solution would be to have a virtual node that just forwards the request to the "real" API that sits behind a router?

And: Is this the right place to ask questions about app mesh? Or should this be part of the roadmap repo?

**Comment by rajal-amzn** [comment]
In addition to what Efe mentioned, if you do not want to use ALB and if you use Route 53 to resolve DNS for App Mesh Virtual Gateway, you could use Route 53's weighted routing policy to split traffic between versions of Virtual Gateways. This is assuming that you want to route between different services for a single path from gateway.
If you want to target different versions of a single service from the gateway, you can configure it using routes in Virtual Service.

**Comment by hffmnn** [comment]
@efe-selcuk @rajal-amzn Thanks a lot for your insights.

> I'm going to move this there, and remove the bug label since there doesn't seem to be an actual problem, though feel free to correct me.

Nothing to correct 😄
