### ISSUE TITLE
Feature Request: Extend preview channels in other regions

### ISSUE THREAD

**Issue by rajal-amzn** [aws/aws-app-mesh-roadmap#186]
**Tell us about your request**
The Preview Channel exposes upcoming features for customers to try as they are developed. Currently the preview channel is available only in `us-west-2`. Customers would want to try it from different regions. Check [this](https://github.com/aws/aws-app-mesh-roadmap/issues/37#issuecomment-611450197) for a recent customer as on this. So, we should extend it to other regions as well.

**Which integration(s) is this request for?**
Preview channel.

**Comment by janaka** [comment]
+1 we are primarily out of `us-east-1`.

**Comment by herrhound** [comment]
Resolving this issue, as we don't plan to extend the preview program to more regions at the moment. Please feel free to reopen if you have additional input.
