### ISSUE TITLE
Bug: Envoy 1.13 > X-Ray integration does not publish all fields

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#189]
**Summary**

When traces from Envoy are published to X-Ray, some fields (http.status, http.content_length as examples) are not published. This is because the raw trace content is being published as strings rather than numbers, which X-Ray is very strict about.

**Comment by dastbe** [comment]
Bug published to Envoy repo: https://github.com/aws/aws-app-mesh-roadmap/issues/189

**Comment by lavignes** [comment]
envoyproxy/envoy#10814

**Comment by dastbe** [comment]
This has been fixed in upstream Envoy, and will be included in our next release of Envoy.
