### ISSUE TITLE
Bug: Console UI notifications do not automatically disappear

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#190]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
Originally [reported on Twitter](https://twitter.com/hugoprudente/status/1250440679110496256?s=20): The current App Mesh console UI has a bug that causes the notifications to stack and not disappear, eventually taking up most of the screen, until manually closed.

Example:
![Example](https://pbs.twimg.com/media/EVp08r_U4AwmdZJ?format=jpg&name=4096x4096)

**Steps to Reproduce**
Perform multiple actions (e.g. creating, updating, or deleting resources) on the AWS App Mesh console, and you will observe this stacking behavior.

**Are you currently working around this issue?**
Manually closing the notifications will remove them from view.

**Comment by ryheath** [comment]
Grouped notifications have been released to the App Mesh console. The user is still required to manually close out notifications, but the grouping greatly reduces the sheer number of notifications presented at any given time.
