### ISSUE TITLE
Feature Request: Retry policy on Virtual Node provider for a Virtual Service

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#194]
**Tell us about your request**
When using a Virtual Node as a [provider for a Virtual Service](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_services.html), you cannot specify the default retry policy you want the clients of your Virtual Service to use. By comparison, Virtual Router providers do allow retry policies to be specified because they are a property of the child [route resources](https://docs.aws.amazon.com/app-mesh/latest/userguide/routes.html).

It would be great to be able to provide a retry policy for the Virtual Node when it is used directly as a Virtual Service provider.

**Which integration(s) is this request for?**
All

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Using a Virtual Node as a provider for a Virtual Service comes with operational risk, as it's not currently possible to define resilience policies (e.g. retries, timeouts) for this configuration. This means that customers will observe more request failures on these Virtual Services.

**Are you currently working around this issue?**
To work around this issue, you can use a Virtual Router provider for the Virtual Service, which allows retry policy definition on its routes.

**Comment by herrhound** [comment]
Resolving this issue due to lack of customer feedback. Feel free to reopen it if you have additional input.
