### ISSUE TITLE
Bug: Console shows DNS discovery type even with Cloud Map

### ISSUE THREAD

**Issue by efe-selcuk** [aws/aws-app-mesh-roadmap#198]
**Summary**

The `Service discovery type` on a virtual node in the console displays `DNS`, even when using Cloud Map. The edit page for the virtual node still shows the correct expected Cloud Map fields.

**Steps to Reproduce**

Create a virtual node with Cloud Map discovery. View it on the console.

**Are you currently working around this issue?**

No workaround at the moment, only a display issue.

We have an engineer currently investigating the bug.

**Comment by awsiv** [comment]
I’ve noticed this as well.

Related: in the ECS console - service page, api only registry is shown AS «external»

**Comment by efe-selcuk** [comment]
@awsiv Could you report that with as much info as possible to https://github.com/aws/containers-roadmap/issues ? Screenshot of what you're referring to would also be helpful.

**Comment by ryheath** [comment]
The fix has been released to the App Mesh console.
