### ISSUE TITLE
Release Envoy v1.14.1

### ISSUE THREAD

**Issue by hugoprudente** [aws/aws-app-mesh-roadmap#211]
The Envoy team released v1.14.1 in April:

https://github.com/envoyproxy/envoy/releases/tag/v1.14.1

We should update the App Mesh Envoy Container Image to use v1.14.1, without the need of re-build the image to use the latest version for the extra support of OpenTracing.

**Comment by LancerRainier** [comment]
We are actively working on 1.15 release for AppMesh'sEnvoy image and we are not planning to release a 1.14 image.

**Comment by hugoprudente** [comment]
@LancerRainier should I re-name the Issue so we can keep track of the 1.15 release and prevent a lot new Feature Requests?
