### ISSUE TITLE
Feature Request: Add arm64 architecture support for App Mesh (envoy)

### ISSUE THREAD

**Issue by buzzsurfr** [aws/aws-app-mesh-roadmap#215]
**Tell us about your request**
Contribute to [envoyproxy/envoy](https://github.com/envoyproxy/envoy) to enable arm64 architecture support for the Envoy container image.

**Which integration(s) is this request for?**
ARM-based instance families (e.g. a1, m6g, c6g, r6g)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to run App Mesh Virtual Nodes on ARM-based instances. Currently, I'm limited to x86_64-based instances.

**Are you currently working around this issue?**
No

**Additional context**
Some work is already being done with Envoy to add arm support.
* https://github.com/envoyproxy/envoy/issues/1861
* https://github.com/envoyproxy/envoy/commit/6c4aae5c293f26a09d260345e31253a79e8ee5e4

**Comment by scottmalkie** [comment]
Bazel binaries for building envoy are now available for arm64, see https://github.com/bazelbuild/bazel/issues/8833 and https://github.com/envoyproxy/envoy/issues/1861 - envoy is just waiting for arm64 test coverage.

**Comment by dastbe** [comment]
Envoy is definitely the big blocker here, but we should also make sure the other artifacts we vend (app mesh proxy route manager, ecs cni, EKS controller(?)) are ARM ready as well.

**Comment by scottmalkie** [comment]
FYI, Envoy just announced official ARM64 support: https://www.envoyproxy.io/docs/envoy/latest/install/building#arm64-binaries

**Comment by kitkit201** [comment]
Any updates on this?

**Comment by RRosalia** [comment]
Is there any update on this subject?

We are really waiting for this image to be released. Btw happy new year everyone!

**Comment by alexbilbie** [comment]
@LancerRainier is there an update on this issue please?

**Comment by RRosalia** [comment]
WE ARE STILL WAITING ON THIS>>> Or at least make it open source so we can do the migration ourself.

**Comment by erikcw** [comment]
Looks like envoy on dockerhub has tagged arm64 builds. 🤞

**Comment by gbhosal** [comment]
Is there any update on this? We are also waiting for this feature.

**Comment by kgns** [comment]
I wonder if the Graviton2 CPUs were just a PR thing as AWS does not really support ARM64 architecture for any serious work load using App Mesh. ECR also has problems with cache manifests for using multiplatform images properly. These issues have been long standing and no one even comments on the future of them.

**Comment by herrhound** [comment]
@kgns, @gbhosal, adding Graviton2 support is a priority for several AWS services, including App Mesh. We started working on an App Mesh-optimized ARM64 Envoy image and you can expect a release before long.

**Comment by gbhosal** [comment]
> @kgns, @gbhosal, adding Graviton2 support is a priority for several AWS services, including App Mesh. We started working on an App Mesh-optimized ARM64 Envoy image and you can expect a release before long.

@herrhound I'm really happy to see the positive update on this issue. Thank you!

**Comment by kgns** [comment]
> @kgns, @gbhosal, adding Graviton2 support is a priority for several AWS services, including App Mesh. We started working on an App Mesh-optimized ARM64 Envoy image and you can expect a release before long.

That is great news! Thanks for the update

**Comment by shaileshgupta2k** [comment]
#381

**Comment by herrhound** [comment]
The ARM64 image is released: https://aws.amazon.com/about-aws/whats-new/2021/11/aws-app-mesh-arm64-envoy-images/
