### ISSUE TITLE
Feature Request: App Mesh-centric Envoy metrics

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#217]
Envoy emits a lot of metrics, but tying those metrics back to what they reference in the App Mesh API requires you to put in a bit of work. For example, the concept of a Virtual Service is effectively lost in the metrics that Envoy emits, instead getting metrics in terms of the Virtual Nodes as Envoy clusters. Given that clients connect and talk to Virtual Services and the destination Virtual Nodes are an implementation detail, customers should be able to reason about metrics in terms of that.

In order to make these metrics easy to consume by customers, we need to emit metrics that are meaningful to customers. While I don't have specifics on what those metrics should look like, they should support the following user scenarios.

* Users should find it easy to generate a set of metrics to monitor based on their listeners backends. These metrics shouldn't have to change with changes to the implementation of their backends.
* Users should be able to incrementally step through metrics as if they're going through their routing itself. They should be able to go from aggregate, to service, to route, to node
* Users should find it easy to monitor all inbound traffic to their Nodes, both locally (at their Node) and remotely (at the clients)

**Comment by herrhound** [comment]
We launched AWS App Mesh Metric Extension: https://aws.amazon.com/about-aws/whats-new/2021/10/aws-app-mesh-metric-extension-available/

Closing this issue.
