### ISSUE TITLE
CloudFormation

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#23]
Add App Mesh to CloudFormation so that customers can easily automate App Mesh setup.

**Comment by rgarcia** [comment]
I see this is "Just Shipped" but are there docs anywhere? I don't see them here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by shubharao** [comment]
It should be available by end of day today

**Comment by christopher-wong** [comment]
As a follow up, are the docs live somewhere?

**Comment by karanvasnani** [comment]
The Cloudformation docs for creating App Mesh resources are now available at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_AppMesh.html

**Comment by renatomjr** [comment]
Any plans to add [proxyConfiguration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_definition_proxyConfiguration) to [AWS::ECS::TaskDefinition](https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html)?
