### ISSUE TITLE
Bug: ENABLE_ENVOY_STATS_TAG does not work for Virtual Gateways

### ISSUE THREAD

**Issue by rajal-amzn** [aws/aws-app-mesh-roadmap#234]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
When we enable `ENABLE_ENVOY_STATS_TAG` to configure AppMesh defined tags in Envoy logs as per the documentation [here](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html), the Virtual Gateways have the following tags:
* `appmesh.mesh` with the mesh name in the value
* `appmesh.virtual_node` with an empty value

Ideally, we should have `appmesh.virtual_gateway` with the Virtual Gateway name.

**Steps to Reproduce**
* Set the Environment variable`ENABLE_ENVOY_STATS_TAG`=1 for the Envoy connecting to Virtual Gateway.

**Comment by rajal-amzn** [comment]
This will be addressed as part of [v1.15.0 Envoy release](https://github.com/aws/aws-app-mesh-roadmap/issues/242)

**Comment by lavignes** [comment]
This is fixed in the [App Mesh Envoy Image](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html) v1.15.0 and up.
