### ISSUE TITLE
Feature Request: Support alternative DNS resolution modes

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#238]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**

Envoy today has two DNS discovery modes: static and logical. Whereas as static assumes the DNS record is an authoritative set of endpoints, logical assumes that the DNS record contains a set of endpoints fronting a load balancer. i.e. w/ logical it's assumed that the destinations will be performing load balancing.

When using DNS-based service discovery, App Mesh configured Envoy to use logical DNS. This was done out of necessity to support Route 53, as it has a hard limitation on the number of endpoints it will return (8). Above that, Route 53 will return a random subset which would cause excessive churn in Envoy as it assumed missing endpoints should be drained.

Obviously, other DNS providers don't have this limitation, ex. kubeDNS can return authoritative results. Today, we recommend customers create a service with a ClusterIP and use that for DNS discovery, as the ClusterIP handles the load balancing.

Why is this even a problem? Because of the way logical DNS works, any improvements we make local to Envoy for health checking, outlier detection, and load balancing are unavailable for DNS users. While we recommend using Cloud Map as the best way of integrating service discovery, we should give our DNS customers the option of having a static DNS experience if their provider supports it.

**Which integration(s) is this request for?**
All

**Comment by rajal-amzn** [comment]
To address this, We propose to add a configuration in Virtual Node’s DNS discovery to specify the type of endpoints returned by the DNS resolver
```
# Virtual Node
{
    "type" : "AWS::AppMesh::VirtualNode", 
    "properties" : 
    { 
        "meshName" : "SampleMesh", 
        "virtualNodeName" : "SampleVirtualNode",
        "spec" :
        {
            "listeners" : [ 
            {
                ...
            } ],
            "serviceDiscovery": {
                "dns": {
                    "hostname": "foo.example.com",
                    #(*NEW*) (*Optional*) Specifies the DNS resolution type
                    #Valid values are LOADBALANCER, ENDPOINTS
                    "responseType": "ENDPOINTS" 
                }
            }
        } 
    } 
}
```
Here, `LOADBALANCER` means that the DNS resolver returns a loadbalanced set of endpoints whereas `ENDPOINTS` means that the DNS resolver is returning all the endpoints. By default, the response type is assumed to be `LOADBALANCER`.

**Comment by rajal-amzn** [comment]
Hello,
The changes are now generally available in all regions. Cloudformation support is yet to be launched. We will update this issue once it is done.

**Comment by rajal-amzn** [comment]
The Cloudformation support for this change are live. Resolving this issue.
