### ISSUE TITLE
Virtual Gateway with TLS disabled shows as `STRICT` mode in console

### ISSUE THREAD

**Issue by jvosantos** [aws/aws-app-mesh-roadmap#240]
**Summary**
When attempting to configure a virtual gateway, the listener by default sets tls mode to Strict. When overriding with tls mode DISABLED, aws fails to execute the command create virtual gateway stating that certificate is a required parameter

**Steps to Reproduce**
```aws appmesh create-virtual-gateway --mesh-name example-mesh --virtual-gateway-name bookinfo --spec '{
  "backendDefaults": {},
  "listeners": [
    {
      "portMapping": {
        "port": 9080,
        "protocol": "http"
      },
      "tls": {
        "mode": "DISABLED"
      }
    }
  ]
}'': exit status 255. Output: 
Parameter validation failed:
Missing required parameter in spec.listeners[0].tls: "certificate"
```

**Are you currently working around this issue?**
Workaround seems to have a configuration with TLS set

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by bcelenza** [comment]
Hey @jvosantos, 

Thanks for filing an issue with us.

To complete disable TLS, we current provide two options. Option 1 is to omit the entire TLS portion of the spec:

```
{
"backendDefaults": {},
  "listeners": [
    {
      "portMapping": {
        "port": 9080,
        "protocol": "http"
      }
    }
  ],
  "serviceDiscovery": {
    "dns": { "hostname": "foo.local" }
  }
}
```

The other option is to have a fully filled out TLS struct, but with the mode set to `DISABLED`:

```
{
"backendDefaults": {},
  "listeners": [
    {
      "portMapping": {
        "port": 9080,
        "protocol": "http"
      },
     "tls": {
       "mode": "DISABLED",
       "certificate": {
         "acm": ...
       } 
     }
    }
  ],
  "serviceDiscovery": {
    "dns": { "hostname": "foo.local" }
  }
}
```

The latter option is provided in case you want to retain all of your TLS settings (which we expect to grow with future releases) while still disabling TLS on the listener.

So in your case, I believe you just want to omit the TLS portion of the struct all together. Hope that makes sense.

**Comment by jvosantos** [comment]
Thank you so much for a quick reply.

I was able to create a Virtual Gateway with TLS disabled indeed, however:
1 - When attempting to create the provided specification, I get error on the key `serviceDiscovery`:

```aws appmesh create-virtual-gateway --mesh-name example --virtual-gateway-name bookinfo --spec '{
  "backendDefaults": {},
  "listeners": [
    {
      "portMapping": {
        "port": 9080,
        "protocol": "http"
      }
    }
  ],
  "serviceDiscovery": {
    "dns": {
      "hostname": "bookinfo.svc.cluster.local"
    }
  }
}'': exit status 255. Output: 
Parameter validation failed:
Unknown parameter in spec: "serviceDiscovery", must be one of: backendDefaults, listeners, logging
```

2 - When ommiting the `tls` block, looking at the AWS Console it states `STRICT` without a certificate configured, I guess this threw me off.
![image](https://user-images.githubusercontent.com/7671252/89110691-3083d700-d445-11ea-8f46-60c8a4c2647e.png)

I was expecting to state `DISABLED` here instead of strict.

**Comment by bcelenza** [comment]
Oh, sorry about the `serviceDiscovery` issue -- I had forgotten that service discovery is not valid in a Virtual Gateway at the moment. Updated my examples above to reflect the correct configuration.

The console value of `STRICT` you're seeing appears to be a bug. I can reproduce it, and verified that the Virtual Gateway was in fact not using TLS, even though the console shows it.

Will leave this issue open until we get that fixed. Thanks for reporting it!

**Comment by jamsajones** [comment]
We have identified the issue and will be fixed in the next console release.
