### ISSUE TITLE
Virtual Gateway should not perform auto rewrite without means to allow for behaviour override

### ISSUE THREAD

**Issue by jvosantos** [aws/aws-app-mesh-roadmap#247]
**Summary**

What are you observing that doesn't seem right?

Hidden in a user guide
https://docs.aws.amazon.com/app-mesh/latest/userguide/gateway-routes.html
and as a comment on github:
https://github.com/aws/aws-app-mesh-roadmap/issues/73#issuecomment-659053467

```If the Match prefix in the gateway route example were /chapter, rather than /, then:

    A request to www.example.com/chapter/page would be re-written to www.example.com/page. Since chapter was the matched prefix, it would be removed in the re-written request.

    A request to www.example.com/chapter1 would be rewritten to www.example.com/1. Again, chapter was removed, since it was the matched prefix, but /1 would be added to the rewritten request from the original request.
```

This in no way makes sense to me. I have two services providing access to different resources, the `potatoes` service, and the `oranges` service.

`potatoes` service has the REST resource `/potatoes`. I am able to perform CRUD operations on potatoes such as:
Create: `POST /potatoes`
Read: `GET /potatoes/{potatoId}`
Update: `PUT /potatoes/{potatoId}`
Delete: `DELETE /potatoes/{potatoId}`

`oranges` service has the REST resource `/oranges`. I am able to perform CRUD operations on oranges such as:
Create: `POST /oranges`
Read: `GET /oranges/{orangeId}`
Update: `PUT /oranges/{orangeId}`
Delete: `DELETE /oranges/{orangeId}`

Given a virtual gateway `rest-virtual-gateway` with two routes:
`potatoes-gateway-route`:

```
{
  "httpRoute": {
    "action": {
      "target": {
        "virtualService": {
          "virtualServiceName": "potatoes.svc.cluster.local"
        }
      }
    },
    "match": {
      "prefix": "/potatoes"
    }
  }
}
```

and

`oranges-gateway-route`:

```
{
  "httpRoute": {
    "action": {
      "target": {
        "virtualService": {
          "virtualServiceName": "oranges.svc.cluster.local"
        }
      }
    },
    "match": {
      "prefix": "/oranges"
    }
  }
}
```

I was hoping that traffic would be routed normally to the services, but instead my service must simply not have the resource it defines and just the id.

To get around this I would need to pollute my API with the service name before the resource because Virtual Gateway is opinionated without any means to override behavior. 

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?
Create the istio bookinfo example on AWS App Mesh.

**Are you currently working around this issue?**
How are you currently solving this problem?

option 1 - A not great at all workaround is polluting REST Api with the service name as to avoid virtual gateway from eating away the path
instead of `api.example.com/potatoes/1` => `api.example.com/potatoes-service-name/potatoes/1` with an HTTP path prefix match of `/potatoes-service-name`
instead of `api.example.com/oranges/1` => `api.example.com/oranges-service-name/oranges/1` with an HTTP path prefix match of `/oranges-service-name`

The option to try and do routing outside of path prefix is nonexistent, so you're not even able to work around this with headers.

option 2 - Don't really use the App Mesh Virtual Gateway, since despite being GA, it lacks a lot of features and basic functionality. Use a virtual node and deploy any gateway of your choosing.

**Comment by rajal-amzn** [comment]
@jvosantos Thanks for providing your usecase. This is an expected behavior.

For the usecase that you have mentioned, you could try creating a GatewayRoute with match prefix "/" and point it to a Virtual Service with 2 Routes - /apples and /oranges and point to the respective services. That way, the prefixes are not auto-written.

We are sorry that it was not evident in the documentation. We will make changes to the docs to make this explicit.

**Comment by rajal-amzn** [comment]
We are tracking path rewrite support for both Gateway routes and Routes [here](https://github.com/aws/aws-app-mesh-roadmap/issues/73). Hence I will close this in favor of that.

**Comment by herrhound** [comment]
Docs updated, the virtual gateway work is tracked here: https://github.com/aws/aws-app-mesh-roadmap/issues/73 Resolving this issue.
