### ISSUE TITLE
Feature Request: Support for specifying AccessLog Format at VirtualNode and VirtualGateway

### ISSUE THREAD

**Issue by karanvasnani** [aws/aws-app-mesh-roadmap#249]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
AppMesh currently allows to configure Path for outputting AccessLogs at the VirtualNode and VirtualGateway however, doesn't allow configuring a format for the logs being generated. Envoy ([access logging](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage)) supports two formats for file access logs: “format strings” and “format dictionaries”. The command operators can be used to extract the relevant data, which can then be inserted into the specified log format resulting in richer logs.

**Which integration(s) is this request for?**
All

**Comment by fawadkhaliq** [comment]
This will prevent customers to do log/trace correlation as the only way to configure that is by adding trace context variables to the access log format. Consider this a blocker for anyone wanting to do trace/log correlation

**Comment by jseiser** [comment]
We currently use App Mesh and Datadog, but we get zero envoy tracing in datadog until this can be corrected.

**Comment by jvosantos** [comment]
Any progress on this?
It's amazing the basic features I search for in a Generally Available production ready products of AWS and they are simply not there.

**Comment by aruandre** [comment]
any updates?

**Comment by EdwardXF** [comment]
**We are now releasing customized Envoy logging format feature!** 
App Mesh now supports defining your own logging pattern for Envoy access logs in TEXT or JSON format.
App Mesh K8s controller and console updated will come soon!
For more details, see here: [Release Announcement](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-app-mesh-introduces-configurable-envoy-access-log-format/)
