### ISSUE TITLE
Feature Request: Support configuration of Envoy TLS parameters

### ISSUE THREAD

**Issue by bigdefect** [aws/aws-app-mesh-roadmap#250]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
App Mesh currently configures Envoy with its default TLS parameters. For the latest Envoy version, they are specified here: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/common.proto

Customers may have specific requirements for TLS negotiation between their services for which the defaults do not suffice, both for envoy-to-envoy traffic and for other services. We could provide APIs to configure TLS protocols, cipher suites, and so on for mesh endpoints.

**Which integration(s) is this request for?**
All

**Comment by buzzsurfr** [comment]
The V3 version is also available at https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto.html#envoy-v3-api-field-extensions-transport-sockets-tls-v3-tlsparameters-cipher-suites

Ideally, this would allow setting a minimum TLS version as well as allowing for a list of cipher suites to be configured. The list would likely be repeated throughout the mesh, but could be useful to have a separate for inside the mesh and for gateways.

**Comment by mahlatsem** [comment]
Hi, 
I see @bigdefect added the label "Awaiting Customer Feedback", apart from the thumbs up, what else would we need?

In my use case, i work for an organisation that has been around for over 150 years, so legacy systems and configs are still prevalent.
One of the changes with Envoy v1.17+ was the removal of weak cipher suites on the client side as per [https://github.com/envoyproxy/envoy/pull/13850/commits](https://github.com/envoyproxy/envoy/pull/13850/commits).

Our challenge is that we still have quite a number of internal/private critical endpoints that services in our mesh connect to which are out of my team's control so while we'll try to push for changes in the organisation, we don't necessarily have the influence that will lead to necessary changes to those services in the immediate future.

One can get around this challenge by setting the TLS parameters configs on Envoy, without support for that on App Mesh, we won't be able to use AppMesh/Envoy v1.17+ which leaves us quite a number of version behind.
