### ISSUE TITLE
Bug: HTTP/2 header names not supported

### ISSUE THREAD

**Issue by moserke** [aws/aws-app-mesh-roadmap#261]
**Summary**
Envoy internally normalizes header names to the HTTP/2 headers, so for example "Host" becomes ":authority".  This can be seen at https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-headermatcher in the note `Internally, Envoy always uses the HTTP/2 :authority header to represent the HTTP/1 Host header. Thus, if attempting to match on Host, match on :authority instead.`

However App Mesh does not allow header names in route matches do not allow the `:`.  They must match the `^[!-9;-~]+$` regex so you can not route on `:authority`.

HTTP/2 header matching/routing should be supported.

**Comment by rajal-amzn** [comment]
@moserke Thanks for reporting. We are currently working on hostname and header match support for Virtual Gateway [here](https://github.com/aws/aws-app-mesh-roadmap/issues/232) where we would be addressing this. 

If we introduce hostname matching at the Virtual Gateway, would you still need hostname matching at Virtual Service? If yes, could you expand on your usecase for hostname matching at Virtual Service?

**Comment by moserke** [comment]
That would solve the need for what I would like to do, which is essentially replace k8s ingress with virtual gateways.  However I do think that this is still somewhat of a bug that Envoy specification allows you to match on HTTP/2 header values, which it normalizes ALL headers to, but app mesh does not allow this because of the regex for header name.  Seems like simply `:` needs to be added to the allowed characters for header name.

I can think of places where people would want this.  Take perhaps a service where it wants to use a single virtual service but send reads to one virtual node and writes to another virtual node, it would do this by routing on the verb which is normalized to `:method`.

Not sure of the underlying reason for leaving the extra character out, but just calling that out as a disconnect with the protocol.

Regarding the virtual gateway routing on header/hostname, what is the timeline for that?

**Comment by rajal-amzn** [comment]
Thanks @moserke For the usecase that you mentioned, we do support matching on `Method` directly in Route specification [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appmesh-route-httproutematch.html) to simplify the UI so that customers do not need to validate Envoy specification when using AppMesh APIs. 

Having said that, I see other usecases where customers might want to match on headers containing `:`. So, we need to fix it.

Regarding the Virtual gateway routing on header/hostname, we are actively working on the design now. We will update the issue with the API proposal once finalized.

**Comment by ganapras** [comment]
Hello.
My customer has the following use case. Looks like it is close to use case mentioned in the comments: **"Having said that, I see other usecases where customers might want to match on headers containing :. So, we need to fix it."**

_"the example that we are trying to do is this... ALB with cnames (serviceA, serviceB). That ALB points to a VirtualGateway with a default route / to a VirtualService. This VirtualService has a VirtualRouter that needs to be able to route to different VirtualNodes based on the original requested hostname (serviceA, serviceB). The standard HTTP1.1 Host header is not available to the inside mesh VirtualService/Router. after some reading it appears as if Envoy normalizes to HTTP/2 headers and takes any inbound HTTP1.1 Host header and converts it to an :authority header on the inside of the mesh. There is not an ability to use the Header matching functionality of the VirtualRouter as the field specified for Header Name doesn't allow ":". It is my understanding that there are also other HTTP/2 headers that start with ":" that  may be useful for Header match routing as well."_

Any timeline on when this will be fixed for header routing on virtual routers

**Comment by rajal-amzn** [comment]
@ganapras 
Thanks for adding your usecase. I have few follow up questions. Is there a specific reason why you want to route based on hostnames from Virtual Service or rather group multiple hostnames under a single Virtual Service?

**Comment by rajal-amzn** [comment]
Thank you everyone for the feedback. At AppMesh, we want to keep our APIs generic. Envoy uses HTTP/2 pseudo-headers to represent other properties of HTTP/1.x requests which is specific to the Envoy implementation. To avoid customers needing to learn Envoy constructs when working with AppMesh, we have decided to not support adding `:` to our headers.

Instead, we are adding support to match on `Hostname` and `Method` directly to [Gateway Routes](https://docs.aws.amazon.com/app-mesh/latest/userguide/gateway-routes.html) based on the customer feedback we have received. Please check the proposal [here](https://github.com/aws/aws-app-mesh-roadmap/issues/232#issuecomment-773911979)

Additionally, we are also adding support to match on `Path` to both [Gateway Routes](https://docs.aws.amazon.com/app-mesh/latest/userguide/gateway-routes.html) and [Routes](https://docs.aws.amazon.com/app-mesh/latest/userguide/routes.html). Please check the proposal [here](https://github.com/aws/aws-app-mesh-roadmap/issues/73#issuecomment-773965240)

Feel free to leave a comment on the proposal directly if you have additional comments.

**Comment by rajal-amzn** [comment]
Resolving this in favor of the proposals mentioned above.
