### ISSUE TITLE
Feature Request: Increase Limits Even More

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#263]
**Tell us about your request**

In issue #110 we performed a first round of limit increases, getting us to the following default service quotas:

Name | Default Limit 
-- | -- 
Backends per virtual node | 50
Connected Envoy processes per virtual node | 50
Gateway routes per virtual gateway | 10
Meshes per account | 15
Routes per virtual router | 50
Virtual gateways per mesh | 3
Virtual nodes per mesh | 200
Virtual routers per mesh | 200
Virtual services per mesh | 200
Weighted targets per route | 10

However, by comparison services like ECS have recently launched support for 2000 services per cluster and 2000 tasks per service. And while Kubernetes doesn't set explicit limits in the way that ECS does, users can achieve the same scale there.

As App Mesh is built to support cross cluster and cross orchestrator configuration, it needs to support not only the limits enabled by a single orchestrator's cluster limits but surpass them, providing an experience that scales to multiple clusters.

**Comment by herrhound** [comment]
We are periodically reviewing our default limits and increasing them. Resolving this issue.
