### ISSUE TITLE
Feature Request: Make maxPendingRequests and optional field in connection pool settings for HTTP

### ISSUE THREAD

**Issue by Y0Username** [aws/aws-app-mesh-roadmap#267]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Currently connection pooling support for [App Mesh circuit breakers](https://github.com/aws/aws-app-mesh-roadmap/issues/6) is released in [preview channel](https://docs.aws.amazon.com/app-mesh/latest/userguide/preview.html).

Under HTTP connection pool settings both `maxConnections` and `maxPendingRequests` are required fields.
We need to make `maxPendingRequests` an optional field and if this field is not specified, we need to set it to a near infinite value (`2147483647`) to disable circuit breaking on pending requests queue.

```
"http": {
    "maxConnections": 500, 
    "maxPendingRequests": 50 --> make this optional
}
```

**Are you currently working around this issue?**
Currently we can set the `maxPendingRequests` to `2147483647` to disable circuit breaking on pending requests queue.

**Comment by jamsajones** [comment]
We will be adding this feature to [ App Mesh circuit breakers ](https://github.com/aws/aws-app-mesh-roadmap/issues/6) for GA release.

**Comment by Y0Username** [comment]
Now the `maxPendingRequests` field is optional.
Updated the preview model with PR https://github.com/aws/aws-app-mesh-roadmap/pull/275.
