### ISSUE TITLE
Bug: outlier detection can't be used with DNS service discovery 

### ISSUE THREAD

**Issue by fawadkhaliq** [aws/aws-app-mesh-roadmap#273]
**Summary**
Envoy in AWS App Mesh uses [logical DNS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery) by default. A cluster in Envoy with logicsl DNS only uses the first IP address returned from the DNS server. So if an application has multiple instances, Envoy will only see one host in the cluster. This limits the outlier detection capability as there's only one host in the cluster at a time. See https://github.com/aws/aws-app-mesh-roadmap/issues/238 for more info. 

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?
1. With DNS service discovery, setup two virtual nodes: `front` and `backend`, where `backend` has four instances.
2. Add `backend` as the backend to the `front` virtual node
3. Enable outlier detection on the `backend` virtual node listener.
4. Inject fault into one of the `backend` instances to return error on each request
5. Generate traffic and you will see that `front` will always have one instance of `backend` in Envoy and outlier detection will not work. 

**Are you currently working around this issue?** 
Yes, use **Cloud Map** service discovery instead of DNS service discovery. This limitation isn't applicable to Cloud Map. 

**Additional context**
None

**Attachments**
None

**Comment by rajal-amzn** [comment]
Resolving this as we now support 2 modes in DNS service discovery for Virtual Nodes as mentioned [here](https://github.com/aws/aws-app-mesh-roadmap/issues/238). Now, outlier detection can be enabled by setting the DNS mode to `ENDPOINTS` in Virtual node.
