### ISSUE TITLE
Feature Request: Use scratch image as base image for Envoy

### ISSUE THREAD

**Issue by lavignes** [aws/aws-app-mesh-roadmap#281]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Today the App Mesh Envoy image is based on [Amazon Linux 2](https://hub.docker.com/_/amazonlinux). This means we pull in whatever base packages are distributed with that image. This makes the image larger than it really needs to be as well as increases the likelihood that [image scans](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html) will report vulnerabilities in libraries that aren't even being used.

**Which integration(s) is this request for?**
All.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Decrease image size, reduce false-positives in vulnerability scans.

**Are you currently working around this issue?**
It could be worked around by making a custom scratch image that just pulled in the binaries from the App Mesh image, but I do not believe that is being done by anyone in practice.

**Comment by suniltheta** [comment]
This should be available in https://github.com/aws/aws-app-mesh-roadmap/issues/407

**Comment by suniltheta** [comment]
App Mesh envoyproxy image starting from v1.22.0 release will be a built on a distroless Docker image.

I you want to use an image with AL2 as base then we have posted a workaround at https://github.com/aws/aws-app-mesh-roadmap/issues/407#issuecomment-1122661513.
