### ISSUE TITLE
Feature Request: Support External Authentication for Ingress

### ISSUE THREAD

**Issue by mveitas** [aws/aws-app-mesh-roadmap#290]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Add support to the app mesh ingress for configuring Envoy external authentication

**Which integration(s) is this request for?**
All

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We are migrating our monolithic API into a smaller set of services and want to start moving authentication out of the application layer and take advantage of the Envoy external auth filter.

**Are you currently working around this issue?**
Looking at a few alternative API gateways solutions

**Comment by rajal-amzn** [comment]
Hey there,
We would need more clarification around your request. From the description of it, it sounds like you are looking to perform external authorization using [AuthZ](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto) filter. If yes, we have an open issue [here](https://github.com/aws/aws-app-mesh-roadmap/issues/140) to track the same.

If not, AppMesh currently supports [TLS](https://docs.aws.amazon.com/app-mesh/latest/userguide/tls.html) and [mTLS](https://docs.aws.amazon.com/app-mesh/latest/userguide/mutual-tls.html) is available for preview. If you are looking for a different mechanism for Authentication like JWT, etc. can you please add your exact usecase?

**Comment by debu99** [comment]
i woud like to use basic auth in appmesh for microservices

**Comment by rajal-amzn** [comment]
@debu99 Could you expand on what you mean by "basic auth"?

**Comment by debu99** [comment]
http basic authentication

Authorization: Basic <credentials>

**Comment by rajal-amzn** [comment]
As mentioned above, We are tracking External Authorization in this issue [here](https://github.com/aws/aws-app-mesh-roadmap/issues/140) We have also added a proposal using OPA. Please take a look at it. If that satisfies what you are looking for, I am going to close this in favor of that one.

**Comment by debu99** [comment]
thanks, opa supports it, May I know eta for opa integration, currently I knew kuma from Kong already supports it

**Comment by rajal-amzn** [comment]
@debu99 We do not commit to timelines externally. Please follow the [issue](https://github.com/aws/aws-app-mesh-roadmap/issues/140) to get more details. We also release the feature in [preview channel](https://docs.aws.amazon.com/app-mesh/latest/userguide/preview.html) before GA. Please watch out for updates in the thread. I am resolving this in favor of the other.
