### ISSUE TITLE
Feature Request: configurable worker threads concurrency of Envoy

### ISSUE THREAD

**Issue by kurochan** [aws/aws-app-mesh-roadmap#292]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**

I want to configure worker threads concurrency of Envoy.

**Which integration(s) is this request for?**

All of the platforms affected.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I have a performance issue that comes from the concurrency of Envoy worker threads.
For example on Amazon ECS,
I assigned 4096 CPU units to the service (with AppMesh Envoy sidecar container) then deployed to c5.4xlarge instance (16 vCPU). I expect Envoy should starts 4 threads.
However, Envoy starts 16 threads because Amazon ECS does not use --cpuset-cpus of Docker, so Envoy sees 16 CPU. This behavior is not performance efficient.

**Are you currently working around this issue?**

Modify `/usr/bin/envoy-wrapper` in AppMesh Envoy container image( https://docs.aws.amazon.com/ja_jp/app-mesh/latest/userguide/envoy.html ).

### before
```
exec /usr/bin/envoy \
    -c "$ENVOY_CONFIG_TMP" \
    --log-level "$ENVOY_LOG_LEVEL"
```

### after

If `ENVOY_CONCURRENCY` is set, then `--concurrency`  pass to Envoy. If not, the behavior is not changed.

```
ENVOY_CONCURRENCY_OPTION=${ENVOY_CONCURRENCY_OPTION:-}
if [ -n "$ENVOY_CONCURRENCY" ]; then
  ENVOY_CONCURRENCY_OPTION="--concurrency ${ENVOY_CONCURRENCY}"
fi

exec /usr/bin/envoy \
    "$ENVOY_CONCURRENCY_OPTION" \
    -c "$ENVOY_CONFIG_TMP" \
    --log-level "$ENVOY_LOG_LEVEL"
```

**Additional context**
Nothing.

**Attachments**
Nothing.

**Comment by suniltheta** [comment]
We have exposed the option to specify the --concurrency via `ENVOY_CONCURRENCY` env variable. This option is available from Envoy version v1.24.0.0-prod https://github.com/aws/aws-app-mesh-roadmap/issues/442

https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy-config.html#envoy-optional-config
