### ISSUE TITLE
Bug: Services cannot communicate using Cloud Map as service discovery in shared mesh

### ISSUE THREAD

**Issue by literalice** [aws/aws-app-mesh-roadmap#294]
**Summary**
In shared mesh environments, a virtual node on an account cannot communicate with a virtual service on another account using Cloud Map as service discovery.

**Steps to Reproduce**

* Follow the walkthrough: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-cross-account
* Change the service discovery to Cloud Map

**Are you currently working around this issue?**
Using DNS as service discovery

**Additional context**
Microservices using http/2 require client side load balancing in many cases. Using Cloud Map is needed to achieve the load balancing in kubernetes environments.

**Comment by rajal-amzn** [comment]
Hi,
Can you give more context into the steps you followed when you changed the Service Discovery to CloudMap? In case you haven't, you need to grant permissions to perform AWS Cloud Map actions to the shared account.

**Comment by karanvasnani** [comment]
@literalice as rajal-amzn mentioned can you check if your secondary account with which the mesh is shared has the Service Linked Role for AppMesh? If not, you can follow the instructions mentioned here to create the role: https://docs.aws.amazon.com/app-mesh/latest/userguide/using-service-linked-roles.html

**Comment by literalice** [comment]
@rajal-amzn @karanvasnani Thank you for replying the issue. I'm not sure we can grant an access permission to a Cloud Map's namespace of another account.
I'll try to give more context into the steps for the issue.

> as rajal-amzn mentioned can you check if your secondary account with which the mesh is shared has the Service Linked Role for AppMesh? 

Yes, In the both AWS account, I have the Service Linked Role for AppMesh ( `AWSServiceRoleForAppMesh` ).

Thank you.

**Comment by rajal-amzn** [comment]
@literalice You do not need to explicitly grant access permissions from Cloudmap's namespace. This is handled internally when the mesh is shared.
The Cross account walkthrough uses registered namespace from Cloudmap and I ran the same walkthrough and modified the mesh `ServiceDiscovery` to `Cloudmap` as shown in this [PR](https://github.com/aws/aws-app-mesh-examples/commit/5b3a5bebc0d968fd1dcefb3805dfda79fa70be17) and it worked.

If you are still facing an issue, could you please share the Envoy logs and the error that you are facing?

**Comment by literalice** [comment]
@rajal-amzn Thank you for your instruction. 
I'd tried your steps using the following repository, I could confirm communicate the each nodes in cross account using Cloud Map.

https://github.com/literalice/aws-app-mesh-examples/tree/crossaccount-cloudmap/walkthroughs/howto-cross-account

Thanks, I close the issue.
