### ISSUE TITLE
 Could not resolve host:

### ISSUE THREAD

**Issue by jtorricorm** [aws/aws-app-mesh-roadmap#295]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**
What are you observing that doesn't seem right?

**Steps to Reproduce**
What are the steps you can take to reproduce this issue?

**Are you currently working around this issue?**
How are you currently solving this problem?

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by karanvasnani** [comment]
Hi @jtorricorm, can you please provide some details about what issue are you facing and details about your setup. The title of the bug ("Could not resolve host:)" doesn't provide any information to us.

**Comment by jamsajones** [comment]
@jtorricorm we are closing this issue due to lack of response. Please feel free to open the issue back up if you are still having the issue and have more details.
