### ISSUE TITLE
Setup iptables via CNI plugin

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#3]
Create a CNI plugin that can be used to route network traffic instead of using containerized proxymanager script that required extra privlages.

**Comment by coultn** [comment]
This is now available on ECS and Fargate, see here:
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html

**Comment by Dhua-v** [comment]
@coultn are there docs available to utilize this cni plugin to configure the iptables.
