### ISSUE TITLE
Bug: GRPC idle timeout has 300 second limit

### ISSUE THREAD

**Issue by mostafafarzane** [aws/aws-app-mesh-roadmap#302]
**Summary**
I have a bidirectional stream service. The client should wait until the server sends some status to it. It may take a while for the server to send something to the client. The client and server are both in Appmesh.
I had set the GRPC idle timeout to 3600 seconds, but after 300 seconds I get `RST_STREAM` error in the client.

**Steps to Reproduce**
I also set the GRPC idle timeout to 5 seconds and I received `RST_STREAM` after roughly 5 seconds. So it seems that GRPC idle timeout works to some extend.

**Are you currently working around this issue?**
I set the keepalive parameter in the GRPC server and client but nothing changed.
BUT, if I send a dummy message from the server to the client every 2 seconds, the problem goes away.

I also want to know is there any way to set the GRPC idle timeout to infinity?

**Comment by shwetasahuit** [comment]
The default idle timeout is 300secs.  If you set a higher timeout, then make sure that the higher value is set for each App Mesh resource in a conversation. For example, if a virtual node backend uses a virtual router provider to route to another virtual node, then the timeout should be set for the source and destination virtual nodes and the route. However if you decrease the timeout from the default value, it can be set only at the route.

Have you only set up the timeout at the route? you need to set 3600s at both participating VN too.

>I also want to know is there any way to set the GRPC idle timeout to infinity?
 
You can set the value to 0, that will disable the timeouts. Make sure to disable it for the VNs too.

**Comment by mostafafarzane** [comment]
> The default idle timeout is 300secs

I have not found anywhere in documents that says the default is 300secs. I had to measure the timeout by myself.

>  the timeout should be set for the source and destination virtual nodes

I have set the idle timeout for both the client and the server side's virtual node.

> Have you only set up the timeout at the route? you need to set 3600s at both participating VN too.

I've should mention that I **do not have** any virtual router/route. The virtual services just connected to their virtual node directly.

> You can set the value to 0, that will disable the timeouts. Make sure to disable it for the VNs too.

I also have tested 0. No difference. I receive `RST_STREAM` after 300 seconds.

**Comment by shwetasahuit** [comment]
The default timeout details are covered in the envoy docs: https://code.amazon.com/reviews/CR-23051357/revisions/1#/details
App Mesh document doesn't mention the default for idle timeouts currently, we will update it.
To modify the default timeouts, you need to setup a virtual router and route in between your virtual nodes. Without setting up a route we don't support changing the default timeouts.
In your scenario, we will suggest you to define a virtual router and a route and set the route idle timeout value and both VN idle timeouts to 0.

**Comment by mostafafarzane** [comment]
I confirm that defining a virtual router between virtual service and virtual node with an idle timeout set to 0 in both the virtual node and virtual router, eliminate 300 seconds default timeout and set it to infinity

 It is nice if you can mention that a virtual router is essential for increasing timeout though.

**Comment by dastbe** [comment]
We're going to keep this open until we get documentation updated, and we're also going to look into whether there are improvements we can make to the Virtual Service -> Virtual Node configuration for gRPC that makes the streaming use case work better.

**Comment by Y0Username** [comment]
We have made doc updates to reflect that timeout value of `0` disables the timeout.

https://docs.aws.amazon.com/app-mesh/latest/userguide/routes.html
https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_nodes.html
