### ISSUE TITLE
Feature Request: Use scratch image as base image for aws-appmesh-proxy-route-manager

### ISSUE THREAD

**Issue by dfezzie** [aws/aws-app-mesh-roadmap#303]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**

Similar to https://github.com/aws/aws-app-mesh-roadmap/issues/281, the `aws-appmesh-proxy-route-manager` image is based on [Amazon Linux 2](https://hub.docker.com/_/amazonlinux). This means we pull in whatever base packages are distributed with that image. This makes the image larger than it really needs to be as well as increases the likelihood that [image scans](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html) will report vulnerabilities in libraries that aren't even being used.

**Which integration(s) is this request for?**

All

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Decrease image size, reduce false-positives in vulnerability scans.

Are you currently working around this issue?

**Are you currently working around this issue?**

It could be worked around by making a custom scratch image that just pulled in the binaries from the App Mesh image, but I do not believe that is being done by anyone in practice.

**Comment by suniltheta** [comment]
The `v4-prod` version that is released https://github.com/aws/aws-app-mesh-roadmap/issues/380 has [eks-distro-minimal-base-iptables](https://gallery.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-iptables) as it's docker base which is in-turn build on [scratch](https://github.com/aws/eks-distro-build-tooling/blob/main/eks-distro-base/Dockerfile.minimal-base-iptables). So we are good to close this issue.
