### ISSUE TITLE
Feature Request: move appmeshworkshop to AWS Organization

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-app-mesh-roadmap#305]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**

The AWS appmesh workshop repository (https://github.com/brentley/appmeshworkshop) does not exist within an AWS organization namespace within GitHub. The AWS organization itself should be responsible for maintaining official repositories as opposed to individual contributors. This ensures customers that the organization itself is fully committed to a project.

**Which integration(s) is this request for?**

All services using AppMesh.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

The problem that should be solved is organizational level support for the AppMesh project.

**Are you currently working around this issue?**

This problem is not currently solved.

**Additional context**

One of the benefits of working with AWS is official support from an entire organization and continuity of commitment and staffing for projects. One-off projects owned by staff at AWS presents a continuity and commitment problem.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by herrhound** [comment]
@brentley - could you please look at this request?

**Comment by colinbjohnson** [comment]
@brentley @herrhound - closing ticket - I see this is now part of the AWS org!
