### ISSUE TITLE
Wrong URL on website.

### ISSUE THREAD

**Issue by mvlbarcelos** [aws/aws-app-mesh-roadmap#31]
I'm not sure if there is here the right place to open this issue, but App mesh [website](https://aws.amazon.com/app-mesh/) is send to invalid URL when click on " Get started with AWS App Mesh". It's sending to :
https://us-west-2.awsc-integ.aws.amazon.com/appmesh/get-started?region=us-west-2

![image](https://user-images.githubusercontent.com/151329/55097235-be1a1e80-50bb-11e9-868b-6245e56b0a3c.png)

**Comment by coultn** [comment]
Fixed!
