### ISSUE TITLE
Bug: XRay not showing MySql traffic with XRay Daemon and App Mesh Fargate setup

### ISSUE THREAD

**Issue by jazztong** [aws/aws-app-mesh-roadmap#310]
**Summary**
I try to set up Service Map consist of Service A -> (Service B) MySql using ECS Fargate stack with AppMesh configuration. To simplify the setup, Service B setup using MySql image instead of RDS.

**Steps to Reproduce**
1. Configure Service A as front API with calling MySql
2. Configure Service B as MySql to allow calls from Service A

**Are you currently working around this issue?**
No Solution

**Attachments**
Backend Configuration for Service A
![image](https://user-images.githubusercontent.com/15000126/106436648-5307b300-64af-11eb-88f7-7feeb1ccbf4d.png)
![image](https://user-images.githubusercontent.com/15000126/106436728-6adf3700-64af-11eb-9a9b-bf79158a3a03.png)
![image](https://user-images.githubusercontent.com/15000126/106436779-79c5e980-64af-11eb-94ca-79a5f2845a3f.png)

**Comment by efe-selcuk** [comment]
To confirm, the traffic between the application and mysql is working, but it's just the traces that aren't? And you are seeing other traces show up in x-ray, and it's just the connections to mysql that aren't?

**Comment by efe-selcuk** [comment]
I asked around just to confirm. But Envoy doesn't support tracing of this kind of traffic (raw TCP), as it won't have any kind of request context (e.g., trace ID). In this case, you'd want to integrate the x-ray SDK into your application (if you haven't already) and instrument the calls to your database. For example: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-sqlclients.html

We could turn this into a feature request. Maybe there's an opportunity to improve Envoy capabilities and provide some metadata for Envoy to be able to trace TCP traffic once it has matched a cluster.

**Comment by karanvasnani** [comment]
There's a similar feature request for the `*.amazonaws.com` tcp traffic [here](https://github.com/aws/aws-app-mesh-roadmap/issues/308), we can maybe extend it to cover this case as well.

**Comment by jazztong** [comment]
> I asked around just to confirm. But Envoy doesn't support tracing of this kind of traffic (raw TCP), as it won't have any kind of request context (e.g., trace ID). In this case, you'd want to integrate the x-ray SDK into your application (if you haven't already) and instrument the calls to your database. For example: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-sqlclients.html
> 
> We could turn this into a feature request. Maybe there's an opportunity to improve Envoy capabilities and provide some metadata for Envoy to be able to trace TCP traffic once it has matched a cluster.

Hi, is that mean AppMesh and Xray only support http request tracing? Is that anywhere mentioned in the documents not support and will be support other protocol tracing? Automatically build up tracing for service map using sidecar give lots possibility for observability for app without modify code.

**Comment by efe-selcuk** [comment]
TCP tracing is supported by App Mesh and X-Ray by way of the SDK and instrumenting the application. TCP tracing doesn't occur "out of the box" like HTTP tracing does for the reasons I mentioned above, but instrumenting your application with X-Ray is recommended even then to get a complete view.

At the very least we do need a documentation improvement on X-Ray and we'll take that up. From a feature perspective I'll make a note in #308 as Karan suggested.

**Comment by lavignes** [comment]
We have recently published some new tracing docs in our User Guide: https://docs.aws.amazon.com/app-mesh/latest/userguide/tracing.html

One thing we're now trying to point out is that application instrumentation is required to see full traces through your services. Distributed HTTP tracing works by passing headers (usually containing an ID representing the trace or a segment thereof) between your services and this is unfortunately not something that can be achieved today without code changes to propagate those headers through your services.

In this case, you'll need to instrument your application to create an X-Ray segment for your MySQL TCP connection.
