### ISSUE TITLE
Feature Request: possibility to keep originate Host header

### ISSUE THREAD

**Issue by twanc** [aws/aws-app-mesh-roadmap#313]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Currently there is not possible to route traffic based on the domain/host header. The header is being replaced by VirtualService hostname. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We would like to route traffic based on standard HOST header to avoid additional extensions to manipulate over custom headers.

**Comment by karanvasnani** [comment]
Hi @twanc, is this request related to allowing hostname and header based routing at the VirtualGateway? In that case will this issue (https://github.com/aws/aws-app-mesh-roadmap/issues/232) solve your use-case?
We're also tracking support to allow configuring host/path rewrites at GatewayRoutes and Routes in this request: https://github.com/aws/aws-app-mesh-roadmap/issues/73.

**Comment by twanc** [comment]
Hi
Both tickets cover my requirements. I hope it will be implemented soon.
Thank you

**Comment by karanvasnani** [comment]
Thanks @twanc for confirming. In that case, I'll close this request.
