### ISSUE TITLE
Feature Request: Support for IPv6

### ISSUE THREAD

**Issue by dastbe** [aws/aws-app-mesh-roadmap#314]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**

Today App Mesh only meaningfully works in IPv4 networks. This has been ok, because most things have only meaningfully worked with IPv4 too. As this is changing, App Mesh needs to determine what IPv6 support means (singlestack only? dualstack?) and define the set of features needed.

While we'll likely cut other issues for specific IPv6 related features, this serves as the top-level issue.

**Comment by AKBarcenas** [comment]
App Mesh has now released general IPv6 support: https://aws.amazon.com/about-aws/whats-new/2022/05/aws-app-mesh-supports-ipv6/

We have added support for single stack IPv6 and dual stack. We have exposed a new IP preference field on our mesh and virtual node APIs to allow the control of how Envoy configuration gets generated with respect to IP version. More can be read about this in our public documentation and we will soon be releasing an example of this feature release in our GitHub repository: https://github.com/aws/aws-app-mesh-examples

**Comment by AKBarcenas** [comment]
An example of IPv6 support in App Mesh can now be found here: https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-ipv6
