### ISSUE TITLE
domains having 301 redirect to upgrade to https are not supported when using http backends

### ISSUE THREAD

**Issue by suyog-fp** [aws/aws-app-mesh-roadmap#317]
**Summary**
When we specify domain which have 301 redirect to https by default then envoy fails to connect to https domain with proper redirect

**Steps to Reproduce** 
All steps and our original discussions are written in
https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/433

**Are you currently working around this issue?**
No, I cant work with domains having 301 redirects
for example stackoverflow.com domain with http backend and tls clientpolicy will not work in service backends as it have 301 redirect to https when tried to connect `http://stackoverflow.com:443`

**Attachments**
original slack discussion https://awsappmesh.slack.com/archives/C0113RB44C9/p1611657084015000

**Comment by efe-selcuk** [comment]
Looks like we have a feature request to track https redirects in https://github.com/aws/aws-app-mesh-roadmap/issues/207

Will close this out and capture it there.
