### ISSUE TITLE
Updating mesh egress filter does not update running Envoys

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#32]
**Summary**

When updating the value of the new [mesh egress filter](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_EgressFilter.html), any Envoy which is currently connected to the App Mesh ADS endpoint will not immediately receive the updated setting. The Envoy will receive the updated configuration after a maximum period of 30 minutes, or after the Envoy disconnects and reconnects to the ADS endpoint.

**Steps to reproduce**
1. Set the mesh egress filter type to ALLOW_ALL to allow all external egress traffic from VirtualNodes.
2. Connect an Envoy identified by a VirtualNode for that Mesh.
3. Update the mesh egress filter type to DROP_ALL to disallow external egress traffic from VirtualNodes.

**Expected behavior**: The Envoy should receive the updated setting within a matter of seconds.
**Actual behavior**: The Envoy does not receive the updated setting until it disconnects and reconnects to the App Mesh ADS endpoint (which happens automatically every 30 minutes).

**Workaround**: You can force the Envoy to update its configuration by restarting it (via the ECS task, EKS pod, or similar). Note that this will need to handled carefully for Envoys serving production traffic (i.e. issue a rolling restart).

A fix has been proposed and will be rolled out over the coming days to address this issue.

**Comment by efe-selcuk** [comment]
A fix for this was rolled out to production regions a couple of months ago. If anyone runs into this again, please open a new issue.
