### ISSUE TITLE
Bug: Envoy failing to serve traffic using SDS when SAN field is empty

### ISSUE THREAD

**Issue by landesherr** [aws/aws-app-mesh-roadmap#331]
**Summary**
Configuration is not correctly updated and nodes are unable to serve traffic when provided with an SDS-based TLS configuration in which the `subjectAlternativeNames` field is empty.

**Steps to Reproduce**
* Create a mesh that uses mTLS with SDS, like the one described by [this example](https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-k8s-mtls-sds-based)
* Remove the `subjectAlternativeNames` field under the TLS configuration for a node's listeners: [like by removing this section of configuration](https://github.com/aws/aws-app-mesh-examples/blob/main/walkthroughs/howto-k8s-mtls-sds-based/v1beta2/manifest.yaml.template#L95)
* Envoy will reject the configuration update, and the node in question will fail to serve traffic

**Are you currently working around this issue?**
Can be worked around by always including a value in the `subjectAlternativeNames` field.

**Comment by shaileshgupta2k** [comment]
This issue is now fixed. Please feel free to re-open if you see it again.
