### ISSUE TITLE
Feature Request: DogStatsD UDS Support

### ISSUE THREAD

**Issue by tobypinder** [aws/aws-app-mesh-roadmap#342]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Dogstatsd currently only supports UDP for transport. For EC2 ECS (and presumably EKS) deployments, it is preferable to connect to daemon services on the host using [UDS sockets](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/?tab=host) instead of routing to an IP. 

**Which integration(s) is this request for?**
ECS, presumably relevant to most/all integrations.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Appmesh [currently supports](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy-config.html) UDP transit via `ENABLE_ENVOY_DOG_STATSD`, `STATSD_PORT` and `STATSD_ADDRESS`. Using something like `STATSD_SOCKET` would enable us to ingest these metrics via the host, without punching holes in networking as configured by the `awsvpc` networking mode.

**Are you currently working around this issue?**
Not currently ingesting `dogstatsd` metrics from envoy due to this.

**Additional context**
* #293 is somewhat relevant as a datadog related issue. 
* [UDS appears to be supported upstream](https://github.com/envoyproxy/envoy/issues/8911) in the `envoyproxy` itself, which may ease implementation.

**Comment by adamdavis40208** [comment]
I'm in the same boat, datadog themselves recommend this "app mesh" way of submitting metrics

https://docs.datadoghq.com/integrations/amazon_app_mesh/?tab=ecsec2

But i'm not entirely sure how that is even supposed to work (magic in the agent, maybe?)

**Comment by suniltheta** [comment]
This is now available starting from App Mesh Envoy image version v1.19.1.0-prod https://github.com/aws/aws-app-mesh-roadmap/issues/369

You can provide the UDS path via `STATSD_SOCKET_PATH` environment variable in the Envoy container. See [AppMesh AWS](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy-config.html) docs for more info.

**Comment by adamdavis40208** [comment]
@suniltheta you're a legend! Thanks y'all!
