### ISSUE TITLE
Support port number in host header

### ISSUE THREAD

**Issue by SantiEich** [aws/aws-app-mesh-roadmap#365]
Hi! I have one service deployed in the EKS cluster including in the Mesh with the following DNS [countries-service.stg.peja.co](http://countries-service.stg.peja.co/)
This service is consumed through the virtual gateway. Our gateway route use match per hostname

![](https://i.ibb.co/CQnrKjP/Untitled.png)

We detected some applications that were consuming this DNS, including the port number on the host. This is due to some libraries
Example: [countries-service.stg.peja.co:80](http://countries-service.stg.peja.co/)
When these applications include the port in the request the host does not match with the gateway route.

Example:

- In this case, we include port

![](https://i.ibb.co/12dVDvN/Screen-Shot-2021-07-22-at-2-13-40-PM.png)

- In this another case we don’t include port

![](https://i.ibb.co/dr9MfQ4/Screen-Shot-2021-07-22-at-2-13-40-PM-copy.png)

To workaround, this issue I tried to create another gateway route with the port included in the host.

![](https://i.ibb.co/sPVxG92/Screen-Shot-2021-08-08-at-10-02-23-PM.png)

But this isn't possible. Also, I tried to create this gateway route through the AWS CLI, but don’t work.

Any possible solution? 

What happens if the services it’s exposed in another not standard port? Example: 8080

Thanks! 😊

**Comment by rajal-amzn** [comment]
@SantiEich Thanks for reporting this. We are analyzing how to support port number in matching hostname in GatewayRoutes. Unfortunately, there is no workaround now.

Regarding your second question on port, services can be exposed in any port. In that case, you would need to define the VirtualNode with a listener on 8080. But if you would still want the clients to call on port 80, you need to define a listener on [VirtualRouter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appmesh-virtualrouter-virtualrouterspec.html) that listens on 80. After that, the clients can send request to `VirtualServiceName:80` and that would get forwarded to port 8080.

**Comment by rajal-amzn** [comment]
We have made changes to allow requests with `Host` header containing port of the Virtual Gateway listener along with allowing `Host` header with just the hostname. No changes are required in the Appmesh configuration. The existing configuration should work. The changes are getting deployed now. We will update here once the change reaches WW.

**Comment by SantiEich** [comment]
Awesome! Thanks so much
Have a good one! 😄

**Comment by lnregalias** [comment]
> We have made changes to allow requests with `Host` header containing port of the Virtual Gateway listener along with allowing `Host` header with just the hostname. No changes are required in the Appmesh configuration. The existing configuration should work. The changes are getting deployed now. We will update here once the change reaches WW.

Will this change allow customers who use AppMesh with EKS to front their VirtualGateway ingress on a custom ELB port?
Currently if a non-standard port is used on the ELB listener, all requests sent via the ELB will have this custom port number as part of the HTTP request host header, and hostname matches do not work correctly. There's also no way to configure this to work since the AppMesh API doesn't currently permit configuring port numbers in the hostname match.

**Comment by rajal-amzn** [comment]
@lnregalias In this case, I assume that the Virtual Gateway listener would be listening on the custom ELB port. That should work since we allow requests with port same as the Virtual Gateway listener.

**Comment by rajal-amzn** [comment]
The fix is now rolled out in all regions. There are no changes required in Virtual Gateway configuration. AppMesh now allows requests with Host header hostname alone as well as hostname and port of the Virtual Gateway listener. Resolving this. Please re-open in case you see any issues.
