### ISSUE TITLE
Bug: Client X-Request-Id being passed without tracer traceIDs cause the request to be un-traceable

### ISSUE THREAD

**Issue by nheaps-chwy** [aws/aws-app-mesh-roadmap#373]
## Summary
Related but not the same issue: #321 
Related AWS support case: 9070869521

We have our virtual gateway accessed in two different ways:

1) CDN -> Site Load Balancer -> Datadog APM enabled service(+envoy), ui-service -> Virtual Gateway -> Mesh enabled service a-service (yes, I know we can save a hop, not the issue here)
2) CDN -> Site load balancer -> Virtual gateway -> mesh enabled service a-service

The CDN, Site Load Balancer, ui-service and a-service all generate and propagate request IDs in the x-request-id header. 

When the path takes 1, then it all works as expected, envoy receives the x-request-id header AND x-datadog-trace-id and x-datadog-parent-id, and the virtual gateway passes it all along as traceable.

When the path takes 2, then the virtual gateway only receives the x-request-id, and envoy does not trust it and subsequently marks the entire request (including all upstream service calls) as untraceable. Metrics still propagate but the trace is lost.

## Steps to Reproduce
Make a request to an envoy instance with x-request-id set but no other headers. With debug logs and datadog turned on, you will see that x-datadog-sampling-priority is forced to be -1, which causes all downstream requests to not trace the request.

## Are you currently working around this issue?
We have temporarily mitigated the issue by moving the x-request-id header at the site load balancer to x-client-trace-id which shows the original request ID in the trace and allows it to be traceable but the upstream applications lose the original request ID.

## Additional context
We also tried to solve this in a number of ways:

* X-envoy-force-trace – This didn’t have an effect as it was trying to trace but something still rejected the tracing mechanism.
* X-Envoy-Internal – this indicates to envoy that the request is coming from within a stack and will be a tad more lenient with the formatting of x-request-id. This didn’t have an effect because envoy sets this based on the presence of the X-Forwarded-For header which is already set by haproxy
* X-Datadog-Sampling-Priority – This didn’t have an effect, envoy/datadog would override it to -1 when it determines the x-request-id cannot be trusted
* X-Datadog-Origin – Datadog sets some context within the tracer based on the presence of this and a trace ID. It did not have an effect
* X-B3-Sampled – Similar to the X-Datadog-Sampling-Priority, datadog listens to this header from other tracing libraries to try and take over the trace on datadog enabled services. It also had no effect
* X-Datadog-Trace-Id and X-Datadog-Parent-Id – setting these is akin to the request coming from another APM enabled service and causes the request to be traced, but datadog blindly accepts them and I don’t have a way of generating a random number that is sufficiently unique. I tried setting the RID here as well but it must be a number
* X-Client-Trace-Id – Setting this will cause the request to be traced (because there’s no request ID) but the upstream services after the gateway will not receive the original request ID from HAProxy. The Envoy Sidecar however will, and it will be tracked in traces.
* Setting APM on and setting sample rate to 1(00%) in the datadog tracer via environment variables. This had no effect
* Setting a secret appmesh environment variable: APPMESH_SET_TRACING_DECISION=0 as guided by the appmesh team. This had no effect but is supposed to disable functionality within envoy which manipulates the x-request-id header.

We also reached out to datadog support and they suggested setting the following in the http_connection_manager, which is directly managed by the appmesh control plane (added in 1.19.0):

```yaml
      stat_prefix: ingress_http
      request_id_extension:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
          pack_trace_reason: false
          use_request_id_for_trace_sampling: false
      route_config:
```

You can find documentation for that here:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=request_id_extension#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-id-extension

In discussions with @rexnp , we both concluded that because this is in the connection manager, a change is needed on the appmesh control plane side. Because it can be a wild goose chase to find a particular node that's configured this way, I suggested to him that it be configured at the mesh level, similarly to how egress is configured for allow/deny all. 

For a fast solution, I would be okay with another secret environment variable that enables/disables this, or an environment variable that gives you more control over the http connection manager parameters but the preferred solution is that it is handled by the mesh.

## Attachments
https://github.com/envoyproxy/envoy/issues/16530
https://github.com/envoyproxy/envoy/pull/16770
https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/request_id/uuid/config.cc#L56

**Comment by jonglim-amzn** [comment]
This feature has been added for the requester. However, it is not a fully supported feature for any customer. If a customer wants to use this feature, we will process and add the requesting customer to our allowed list upon request.
