### ISSUE TITLE
Feature Request: aws_request_signing:Add ability to exclude headers during signing

### ISSUE THREAD

**Issue by nisheedhr** [aws/aws-app-mesh-roadmap#375]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Currently aws_request_signing, signs all the headers. Users of this extension should have an ability to specify the headers to be excluded during signing.  This idea was briefly discussed in https://github.com/envoyproxy/envoy/pull/18729#issuecomment-951130418.

**Which integration(s) is this request for?**
We have use cases where we don't want JWT token headers to be not signed ,as the token is already signed.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
With the current mechanism, users have to pay the penalty of signing headers which don't require signing.  Exclude mechanism provide users the flexibility to choose which headers to sign.

**Are you currently working around this issue?**
No work around available. We are currently signing all headers.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by abaptiste** [comment]
Associated Pull Request:  https://github.com/envoyproxy/envoy/pull/18998

**Comment by arafatm-aws** [comment]
we will wait till latest envoy merges the PR before closing

**Comment by abaptiste** [comment]
The linked pull request has been merged into Envoy and is available in the standalone Envoy. 

Since using Envoy inside AppMesh does not rely on this feature, I am closing this request.  Please feel free to reach out to us via Slack/GitHub if you need any further assistance.
