### ISSUE TITLE
Feature Request: Aggregate  X-ray segments of cross account EKS Envoy containers to specific account

### ISSUE THREAD

**Issue by jaga810** [aws/aws-app-mesh-roadmap#382]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Add option to specify IAM Role ARN  to upload segments to a different account described in [1] to the command below.

```
helm upgrade -i appmesh-controller eks/appmesh-controller 
\ --namespace appmesh-system 
\ --set tracing.enabled=true 
\ --set tracing.provider=x-ray
\ --set tracing.role={Role ARN} # Now there is no option to specify IAM Role. This is expected implementation.
```

[1] https://github.com/aws/aws-xray-daemon

**Which integration(s) is this request for?**
EKS

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

If you try tracing using X-ray with EKS stack in multi account environment, you need to see X-ray console in each accounts.
This feature request enables us to aggregate X-ray segments of cross account EKS Envoy containers to specific account.
X-ray daemon has the option to specify IAM Role to upload segments to a different account [1].
However App Mesh EKS controller has no option to specify IAM Role so far [2].

[2] https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/README.md#configuration

**Are you currently working around this issue?**
No working around found.

**Additional context**
I try to use App Mesh with Amazon EKS in a Multi-Account environment referencing [3].
[3] https://aws.amazon.com/jp/blogs/containers/leveraging-app-mesh-with-amazon-eks-in-a-multi-account-environment/

**Attachments**
N/A

**Comment by suniltheta** [comment]
There is a PR [#554](https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/554) on `aws-app-mesh-controller-for-k8s` repo which should address this concern. I have also created a controller image at `public.ecr.aws/y0u8t6t1/appmesh-controller:v1.4.3` (AMD64) with the patch. Feel free to test and add your suggestions.


To pick the image you probably need to do the following
```
git clone -b configure_xray_agent https://github.com/suniltheta/aws-app-mesh-controller-for-k8s.git
cd aws-app-mesh-controller-for-k8s
helm upgrade -i appmesh-controller config/helm/appmesh-controller/ \                                     
    --namespace appmesh-system \
    --set tracing.enabled=true \
    --set tracing.provider=x-ray --set tracing.role=arn:aws:iam::<ACCOUNT_ID>:role/xray-cross-account \
    --set tracing.logLevel=dev \
 --set image.repository=public.ecr.aws/y0u8t6t1/appmesh-controller --set image.tag=v1.4.3
```
`<ACCOUNT_ID>` here is the specific account on which x-ray traces needs to be uploaded.

**Comment by suniltheta** [comment]
Now that https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/554 is merged, this support should be available in the next controller release v1.4.3+ or v.1.5+

**Comment by jaga810** [comment]
@suniltheta 
Thank you. This PR looks amazing.

However, I tried your implementation using eks/appmesh-controller v1.4.4. as ChartVersion and v1.4.2 as AppVersion and didn't work well.
Which do you mean ChartVersion or AppVersion by mentioning v1.4.3+ or v.1.5+?

**Comment by suniltheta** [comment]
The controller image or the helm chart with these changes are not released yet.

If you want to experiment you can try the steps I mentioned in previous https://github.com/aws/aws-app-mesh-roadmap/issues/382#issuecomment-1011333581.

**Comment by jaga810** [comment]
@suniltheta 
```shell
$ git clone -b configure_xray_agent https://github.com/suniltheta/aws-app-mesh-controller-for-k8s.git
Cloning into 'aws-app-mesh-controller-for-k8s'...
fatal: Remote branch configure_xray_agent not found in upstream origin
```

The branch looks already closed.

**Comment by suniltheta** [comment]
Probably I might have deleted that branch without realizing. I just updated the commands.

**Comment by jaga810** [comment]
Though I followed the updated commands, app mesh container sends x-ray logs to the account where container deployed not the account specified by `--set tracing.role=arn:aws:iam::<ACCOUNT_ID>:role/xray-cross-account`.

```shell
helm list -n appmesh-system
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
appmesh-controller      appmesh-system  1               2021-11-18 09:04:56.785881185 +0000 UTC deployed        appmesh-controller-1.4.2        1.4.1
```

**Comment by suniltheta** [comment]
I just want to confirm if you have setup proper permission between these two account.

Let's say you have two accounts

Account_A <-- running the cluster, where container are deployed
Account_B <-- where xray traces are destined.


### Inside Account_B console:
You will create a role say `arn:aws:iam::<Account_B>:role/xray-cross-account` by including Trusted entities: The account Account_A. You will attach the policy `arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess` to this role.

### Inside Account_A console
Create a policy by name say `AWSXRayDaemonCrossAccountWriteAccess` with policy json defined like this
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::Account_B:role/xray-cross-account"
        }
    ]
}
```

Next attach this policy `arn:aws:iam::Account_A:policy/AWSXRayDaemonCrossAccountWriteAccess` for the node instance role that holds your deployment.

If you need further assistance feel free to reach me at "sunitheta" on [AppMesh slack channel](https://github.com/aws/aws-app-mesh-roadmap#slack-community)

**Comment by suniltheta** [comment]
Closing this issue as Controller [v1.5.0](https://github.com/aws/aws-app-mesh-controller-for-k8s/releases/tag/v1.5.0) is released with this fix.
