### ISSUE TITLE
Feature Request: Enable Load Shedding capability

### ISSUE THREAD

**Issue by ricardosouzamorais** [aws/aws-app-mesh-roadmap#388]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
What do you want us to build?
Implement a way, load shedding mechanism, to control the admission of requests in order to not degrade the workload's components that are delivering content up to a limit that they can.

Some references:
- https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/
- https://aws.amazon.com/blogs/networking-and-content-delivery/target-group-load-shedding-for-application-load-balancer/
- https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/admission_control_filter.html?highlight=load%20shedding

**Which integration(s) is this request for?**
This could be Fargate, ECS, EKS, EC2, Kubernetes, something else.
My use case is for ALB, but I think it could be any load balancer, or mechanism that delivers content as a Virtual Node.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

My application is exposed through App Mesh, and I want to be able to stop to receive traffic if I am not able to spin more instances into my ASG, for example, due to any reason like (lack of instance type, failure on bootstrap process, or something else).

**Are you currently working around this issue?**
How are you currently solving this problem?
Thinking about implement the first link that is shared into the references right above.

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by herrhound** [comment]
@ricardosouzamorais, would connection pooling functionality solve your use-case? From the [docs](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_nodes.html):

_Connection pooling limits the number of connections that an Envoy can concurrently establish with the local application cluster. It is intended to protect your local application from being overwhelmed with connections and lets you adjust traffic shaping for the needs of your applications._

**Comment by herrhound** [comment]
Closing the request due to inactivity – I believe that today App Mesh addresses the ask via connection pooling.
