### ISSUE TITLE
TCP routing

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#4]

**Comment by bobeagan** [comment]
Plans for UDP support get abandoned? Saw the title was changed but don't see a new issue created for supporting it down the road.

**Comment by jtoberon** [comment]
@bobeagan Not abandoned, but UDP is not yet supported in Envoy. I will open a separate issue to track UDP support in App Mesh.

**Comment by jtoberon** [comment]
I created https://github.com/aws/aws-app-mesh-roadmap/issues/57 to track the UDP feature
