### ISSUE TITLE
Enable ECS with other networking modes

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#40]
In ECS awsvpc networking mode doesn't meet everyone's needs. Enabling other network modes would be great.

**Comment by coultn** [comment]
Hi everyone, FYI we have an upcoming launch for ECS that will increase the number of ENIs on ECS when using awsvpc networking mode on nitro-based instances.  This will help make it easier to use App Mesh with awsvpc networking on ECS:  https://github.com/aws/containers-roadmap/issues/7

**Comment by shubharao** [comment]
We now have increased task limits when using awsvpc task networking mode. This let you go up to 120 tasks per instance, depending on instance type. More details [here](https://aws.amazon.com/about-aws/whats-new/2019/06/Amazon-ECS-Improves-ENI-Density-Limits-for-awsvpc-Networking-Mode/) and [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html) 
Based on this, we do not have plans to support other networking modes in the near term roadmap. If this is a concern for you, please open a new issue. Thanks!
