### ISSUE TITLE
Enable Envoy FIPS 140-2 support for SSL as option or default

### ISSUE THREAD

**Issue by eoliphan** [aws/aws-app-mesh-roadmap#410]
*If you want to see App Mesh implement this idea, please upvote with a :+1:.*

**Tell us about your request**
Envoy supports FIPS-140-2 compliant SSL via a build option on the underlying BoringSSL lib. See [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#fips-140-2)

**Which integration(s) is this request for?**
Fargate, ECS, EC2

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Our environment requires FIPS-140-2, and there doesn't appear to be a way to enhance/extend the envoy image used by AppMesh (an alternative solution might be making the default build/Dockerfile(s)/etc available on GitHub and allowing one to specify a customized image in your AppMesh config) 

**Are you currently working around this issue?**
At the moment there doesn't appear to be a workaround that includes AppMesh

**Additional context**
N/A

**Attachments**
N/A

**Comment by GHutchinsonAtGrantsolutions** [comment]
@suniltheta Do you have an ETA for the FIPS140 images?

**Comment by egkelly** [comment]
I also have this requirement. Is there any plan to add this into the roadmap?

**Comment by rajarshidas** [comment]
https://github.com/aws/aws-app-mesh-roadmap/issues/479

"For regions where AppMesh FIPS endpoint is supported https://docs.aws.amazon.com/general/latest/gr/appmesh.html

840364872350.dkr.ecr.<region>.amazonaws.com/aws-appmesh-envoy:v1.27.0.0-prod-fips
e.g.

840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.27.0.0-prod-fips"

**Comment by egkelly** [comment]
Thanks!

**Comment by suniltheta** [comment]
Although Envoy supported FIPS mode using BoringSSL the certificate issued to BoringSSL is not tested on AWS environment. Hence we had to build the Envoy binary by using AWS-LC in FIPS mode. This was possible with the help of support from [AWS-LC](https://github.com/aws/aws-lc) team

&nbsp;

> cc: @billbo-yang @andrewhop, @darylmartin100 @compgeeksquires @shsahu @shenjianan97 @herrhound

**Comment by rajarshidas** [comment]
@suniltheta Should this issue be closed now?
