### ISSUE TITLE
Bug: Consistent Connection Resets, easily reproducible, failing http connections

### ISSUE THREAD

**Issue by Psynbiotik** [aws/aws-app-mesh-roadmap#415]
**Summary**
After using multiple connections, waiting 10 minutes, any following http connection after will fail in about 1 ms.

**Steps to Reproduce**
[Pure npm AWS CDK demo of the issue](https://github.com/Psynbiotik/appMeshSocketResetIssue)
This project uses AWS CDK to create a from scratch app mesh deployment to demonstrate the issue.

This project has several parts:
The README has some info about how to run and prerequisites needed (npm & cdk)
The cdk startup script in lib/app_mesh_issu_stack.ts
An App mesh that does not allow outside connections. There is no route to the app mesh as it is not needed for this demonstration
A single container in the app mesh, this is the 'fargete' directory.
A single lambda, this is the 'lambda' directory.

All components are bare bones. The lambda is nothing more then a hello world. The fargate container only contains a health check endpoint and a loop where it calls the lambda 1000 times in quick succession, pauses for 10 minutes then makes a few calls to illustrate the issue.

When looking at the logs you can search for '-----' to find the break between the inital calls and when the failures begin. You should see about 14 failures then success again.

**Are you currently working around this issue?**
We are attempting multiple retries when we see this issue, 30 retries is enough to break through, since each failure is about 1-2 ms we can quickly roll through the expired connections until we get some fresh ones.

However this problem is pervasive and we are playing wack a mole when we see this issue pop up.

**Additional context**
You can launch the script by running 'run.sh'
I believe the issue is some kind of connection pooling holding connections for too long, but as you can see I've got no pooling in my app and I've also disabled all pooling in my app before using the environmental variable AWS_NODEJS_CONNECTION_REUSE_ENABLED=false, this did not help the issue and only made my calls take longer.

Failures from app log:
{
    "level": 50,
    "time": 1655140602278,
    "pid": 30,
    "hostname": "ip-10-0-253-250.ec2.internal",
    "msg": "failed with ECONNRESET on invocation: 1009"
}

Failures from envoy log:
...
[2022-06-13 17:16:41.026][43][debug][connection] [source/common/network/connection_impl.cc:250] [C30] closing socket: 0
[2022-06-13 17:16:41.026][43][debug][pool] [source/common/conn_pool/conn_pool_base.cc:439] [C30] client disconnected, failure reason: 
[2022-06-13 17:16:41.026][43][debug][pool] [source/common/conn_pool/conn_pool_base.cc:410] invoking idle callbacks - is_draining_for_deletion_=false
[2022-06-13 17:16:41.026][43][debug][pool] [source/common/conn_pool/conn_pool_base.cc:210] [C30] destroying stream: 0 remaining
[2022-06-13 17:16:41.026][43][debug][pool] [source/common/conn_pool/conn_pool_base.cc:410] invoking idle callbacks - is_draining_for_deletion_=false
[2022-06-13 17:16:41.026][43][debug][connection] [source/common/network/connection_impl.cc:139] [C29] closing data_to_write=0 type=0
[2022-06-13 17:16:41.026][43][debug][connection] [source/common/network/connection_impl.cc:250] [C29] closing socket: 1
The log groups contain the logs from the envoy container and the app itself, 

**Attachments**
I've included a zipped version of the from scratch issue demo app as well.
[appMeshIssue.zip](https://github.com/aws/aws-app-mesh-roadmap/files/8893361/appMeshIssue.zip)

**Comment by csydvs** [comment]
Seeing a similar issue with my app connecting to Redis. Setting up a new node with a service backend for my Redis instance, everything looks good, and then after 8-10 mintues, start getting ECONNRESET issues when trying to reach out to my redis cluster. Would love to see a fix here.

**Comment by rs98101** [comment]
I've run into this as well. We're loving the app mesh except for this issue.

**Comment by blained3** [comment]
This would make my life SOOO much easier! Constantly having to cycle through connections is a pain.

**Comment by mikeUtah** [comment]
Ugh... we appear to be running into this issue as well. Programatically working around this is pretty ugly. Any idea if this is going to be picked up?

**Comment by amanwaring** [comment]
@shsahu how is the research going on this one? This is affecting my application

**Comment by UndyingSoul** [comment]
Anyone have any solutions for this? We're running into this same issue. Is Amazon ever going to get to this? Or are we just going to have to implement retries for Every. Single. Connection.

**Comment by awsjdgls** [comment]
This is caused by the default AWS route overriding the custom route, which you can read about in the [troubleshooting guide][1]: 

> App Mesh does not currently allow multiple backend destinations modeled as TCP to share the same port due to restrictions in the information provided to the Envoy proxy at OSI Layer 4.

Since the default route takes precedence, the custom idle timeout settings do not take effect.  Please see #195 for a discussion, including [a workaround][2].

[1]: https://docs.aws.amazon.com/app-mesh/latest/userguide/troubleshooting-connectivity.html#ts-connectivity-virtual-node-router
[2]: https://github.com/aws/aws-app-mesh-roadmap/issues/195#issuecomment-870796987
