### ISSUE TITLE
Bug: `tr: command not found`

### ISSUE THREAD

**Issue by keigohtr** [aws/aws-app-mesh-roadmap#421]
**Summary**
`proxyinit` which is "Init Containers" of envoy of appmesh raised following message. Our situation was that we were using appmesh-controller of helm chart version 1.3.2, and have upgraded to the chart version 1.5.0.

```
=== Input configuration ===
declare -x APPMESH_APP_PORTS="xxx"
declare -x APPMESH_EGRESS_IGNORED_IP="xxx"
declare -x APPMESH_EGRESS_IGNORED_PORTS="22,22"
declare -x APPMESH_ENABLE_IPV6="1"
declare -x APPMESH_ENVOY_EGRESS_PORT="xxx"
declare -x APPMESH_ENVOY_INGRESS_PORT="xxx"
declare -x APPMESH_IGNORE_UID="xxx"
declare -x APPMESH_START_ENABLED="1"
=== Initializing ===
=== Enabling routing ===
/opt/amazon/bin/sidecar-proxy-route-manager.sh: line 70: tr: command not found
=== Entering main loop ===
```

**Steps to Reproduce**
- EKS 1.21

**Are you currently working around this issue?**
Although the message was raised, it's still working. 

```
Init Containers:
  proxyinit:
    Container ID:   docker://e194242bbdef567c70245c19993092adf9fb6be33c98cb3ae4c5de0d8533b628
    Image:          840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager:v5-prod
    Image ID:       docker-pullable://840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-proxy-route-manager@sha256:87e91f73b05e4ff33afe6c0f0014174e27d970ff23505ae1c5f2541b76e48a51
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 04 Jul 2022 10:32:22 +0900
      Finished:     Mon, 04 Jul 2022 10:32:22 +0900
    Ready:          True
 ```

**Additional context**
N/A

**Attachments**
N/A

**Comment by suniltheta** [comment]
This is a bug in the init container image with the usage of variable `APPMESH_EGRESS_IGNORED_IP`. We will soon get back with a workaround.

**Comment by suniltheta** [comment]
Can you test with this image `public.ecr.aws/suniltheta/aws-appmesh-proxy-route-manager:v6-test` (ECR public [link)](https://gallery.ecr.aws/suniltheta/aws-appmesh-proxy-route-manager) and confirm that you don't run into the same issue? I have included the missing command into this image. 


```
helm upgrade -i appmesh-controller eks/appmesh-controller \
    --namespace appmesh-system \
    --set init.image.repository=public.ecr.aws/suniltheta/aws-appmesh-proxy-route-manager \
    --set init.image.tag=v6-test
```

Please note that this is not an official workaround. We will soon release an official v6-prod image.

**Comment by keigohtr** [comment]
Thanks @suniltheta for your help. I will try it and get back to you.

**Comment by keigohtr** [comment]
@suniltheta Hi,
I have tried the image you created for me. I have checked the image has `tr` command. But It didn't work in another reason... The message was

```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/controller": stat /controller: no such file or directory: unknown
      Exit Code:    127
```

**Comment by suniltheta** [comment]
I believe this error was returned by the App Mesh K8s controller container. You might have accidentally updated the 
`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller` ?

```
$ kubectl describe deploy/appmesh-controller -n appmesh-system | grep -i image
    Image:       602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/appmesh-controller:v1.5.0
      --sidecar-image=840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.22.2.0-prod
      --init-image=public.ecr.aws/suniltheta/aws-appmesh-proxy-route-manager:v6-test
      --xray-image=public.ecr.aws/xray/aws-xray-daemon:latest
```

If you want we can continue discussion offline, feel free to ping me on App Mesh [slack channel](https://github.com/aws/aws-app-mesh-roadmap#slack-community) `@suniltheta`

**Comment by keigohtr** [comment]
yeah you are correct. I made a mistake.
It worked without error message. Thanks and will looking forward to the release.

**Comment by suniltheta** [comment]
A new version v6-prod is released. For workaround you can upgrade the proxyinit container version from helm 
```
helm upgrade -i appmesh-controller eks/appmesh-controller --namespace appmesh-system --set init.image.tag=v6-prod
```

or directly edit the appmesh-controller deployment spec to set `--init-image` version to v6.
```
kubectl edit deploy/appmesh-controller -n appmesh-system
```


We will keep this issue open and close it when a new version of AppMesh controller for k8s is released https://github.com/aws/aws-app-mesh-controller-for-k8s/releases containing v6-prod or later as default.

**Comment by keigohtr** [comment]
@suniltheta 
wow! Thanks a lot!
We are looking forward to releasing a new version of AppMesh Controller!

**Comment by suniltheta** [comment]
A new version of controller image is release with [v1.5.1](https://github.com/aws/aws-app-mesh-controller-for-k8s/releases/tag/v1.5.1). I will go ahead and close this issue.
