### ISSUE TITLE
Bug: Couldn't determine the AZ ID due to: unable to fetch placement/availability-zone-id from IMDSv1

### ISSUE THREAD

**Issue by nwsparks** [aws/aws-app-mesh-roadmap#427]
*SECURITY NOTICE: If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).*

**Summary**

Envoy (both standalone and as a sidecar) logs this error 

`level=error msg="Couldn't determine the AZ ID due to: unable to fetch placement/availability-zone-id from IMDSv1, Get \"http://169.254.169.254/latest/meta-data/placement/availability-zone-id\": dial tcp 169.254.169.254:80: connect: invalid argument"`

**Steps to Reproduce**

Launch any envoy container in fargate. unsure if this also occurs on ec2

**Are you currently working around this issue?**

It's not blocking startup, but would be nice to resolve the issue

**Additional context**

Only tested on fargate

**Comment by suniltheta** [comment]
Hi, this should have been a warning message instead of error. We can fix this in next envoy release v1.23

Just curious, if this would this cause any alarm?

**Comment by nwsparks** [comment]
Is there any way to resolve it so that the error/warning stop appearing? It doesn't seem to be hurting anything but would be nice to get the logs error free.

**Comment by suniltheta** [comment]
Unfortunately, no workaround today. The problem is due to trying to access IMDS from inside ECS container to build an optional metadata.
