### ISSUE TITLE
Fix 503 responses from Envoy when adding a new route

### ISSUE THREAD

**Issue by ivitjuk** [aws/aws-app-mesh-roadmap#43]
**Describe the bug**

See https://github.com/envoyproxy/envoy/issues/5174 for the detailed description.

**Platform**
ALL

**Expected behavior**
Should not return 503 on route change.

**Additional context**
https://github.com/envoyproxy/envoy/issues/5174

**Comment by efe-selcuk** [comment]
Resolving this. A PR was made to alleviate this issue: https://github.com/envoyproxy/envoy/pull/5887
