### ISSUE TITLE
Accessing host instance

### ISSUE THREAD

**Issue by achandras** [aws/aws-app-mesh-roadmap#46]
Hello, I was wondering what would be the correct way to access the host on which a service is running. It would be cumbersome to model each host as a TCP virtual node and virtual service and add them all as backends to each service to account for dynamic task placement. 

My initial thought is to add them to the APPMESH_EGRESS_IGNORED_IP since that's how the metadata services are reached, but I wanted to know if there was a better approach.

Thanks!

**Comment by dastbe** [comment]
Hey @achandras 

A few questions

1. Is your goal to connect to individual hosts from within App Mesh (being proxied by an Envoy) or as an external application?
2. Are you trying to uniquely identify an individual host? or do you just need to know all of the hosts and make connections to them?

If your specific use case is "I want to access individual hosts from a process that is proxying through Envoy" then you will have to use APPMESH_EGRESS_IGNORED_IP, passing the IP(s) or CIDR ranges of your directly routable endpoints. With TCP routing, you are still limited to having a single TCP Virtual Service on any given port.

Note that using option will ignore **all** traffic on that ip, regardless of whether you have other routing rules for that hostname.

**Comment by herrhound** [comment]
Resolving the old issue as part of the cleanup. Feel free to reopen it if you have additional input.
