### ISSUE TITLE
App Ports should not be required

### ISSUE THREAD

**Issue by nckturner** [aws/aws-app-mesh-roadmap#48]
**Describe the bug**
Currently aws-appmesh-proxy-route-manager assumes that it is setting up iptables rules for a service and requires the environment variable APPMESH_APP_PORTS to be set.  However, there is a use-case for using envoy as a side-car to an application that is client only and has no open ingress ports.  In this case, the user would have to specify a fake port in order to launch the pod.

**Platform**
EKS, ECS

**To Reproduce**
1. Run aws-appmesh-proxy-route-manager without APPMESH_APP_PORTS set.

**Expected behavior**
APPMESH_APP_PORTS should be able to be unset, perhaps with a warning message printed.

**Comment by LancerRainier** [comment]
We are actively working on this and pending release for EKS. we will be looking into the ECS part as a quick follow up to this issue.

**Comment by flashyang** [comment]
We have released a fix for this for EKS

**Comment by bcelenza** [comment]
With the merge of https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/321, customers using App Mesh on EKS with EC2 nodes will be able to omit app ports for egress-only virtual nodes.

The remaining work before this can be closed:
1. Roll out the change for the [CNI plugin](https://github.com/aws/amazon-vpc-cni-plugins/pull/37) to Fargate nodes for both EKS and ECS
2. Remove the requirement for `AppPorts` and `ProxyIngressPort` on the [ECS ProxyConfiguration API](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html).

**Comment by lavignes** [comment]
Going to close this out now. https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html
In ECS this option is still *required* but you can now specify and empty list.
