### ISSUE TITLE
AWS re/start program - Egypt - sprints - bug

### ISSUE THREAD

**Issue by NourrAssem** [aws/aws-app-mesh-roadmap#498]
Hello team,

I’m facing 2 issues with AWS re/start program when I select **Egypt** as country ( https://aws.amazon.com/training/restart/ )

The first issue: when I try to open “sprints” hyperlink, website isn’t found.
I receive this error “ Not Found
The requested URL was not found on this server.“

The second issue: when I open “ Information Technology Institute”, there is no application to register in.

Thanks,
Nour

**Comment by joesbigidea** [comment]
This roadmap is specific to the [AWS App Mesh service]( https://docs.aws.amazon.com/app-mesh/latest/userguide/what-is-app-mesh.html). It sounds like you're having an issue specific to some AWS training. There's a [contact us](https://support.aws.amazon.com/#/contacts/aws-restart) link on that page that  would probably be the best way to report your issue.
