### ISSUE TITLE
Provide the Envoy software in each region where App Mesh is available

### ISSUE THREAD

**Issue by jtoberon** [aws/aws-app-mesh-roadmap#56]
You should not have to do cross-region pulls in order to deploy the Envoy sidecar. Cross-region traffic can affect both performance and availability.

**Comment by Y0Username** [comment]
Envoy image is now available in all the regions where AppMesh is available with URI: 

`111345817488.dkr.ecr.`_region_`.amazonaws.com/aws-appmesh-envoy:v1.11.1.0-prod`


Example:
```
$(aws ecr get-login --region us-east-1 --no-include-email)
docker pull 111345817488.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.11.1.0-prod
```

**Comment by ehough** [comment]
Potentially stupid question, could anyone tell me why I can't pull this image from any region?

```
$(aws ecr get-login --no-include-email)
docker pull 111345817488.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.11.1.0-prod
```
Results in an error:
```
Error response from daemon: Get https://111345817488.dkr.ecr.us-east-1.amazonaws.com/v2/aws-appmesh-envoy/manifests/v1.11.1.0-prod: no basic auth credentials
```

**Comment by bcelenza** [comment]
@ehough Try this login command instead:

`$(aws ecr get-login --no-include-email --registry-ids 111345817488)`

Hopefully that resolves the issue.

**Comment by ehough** [comment]
> `$(aws ecr get-login --no-include-email --registry-ids 111345817488)`

That worked, thank you @bcelenza :tada: 

The [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors-docker.html#error-403) talk about pushing to an ECR repo, but I should've figured it would be the same solution for pulling.

**Comment by bcelenza** [comment]
@ehough Sweet! I've submitted some feedback on the documentation you linked to get it reworded to include pull as well :)
