### ISSUE TITLE
Bring AppMesh under PCI Scope

### ISSUE THREAD

**Issue by manikawnth** [aws/aws-app-mesh-roadmap#75]
We're excited about the features of aws app mesh. 
But our org's cloud policy is to adopt aws services which are PCI compliant.

AWS app mesh is still not under PCI compliance.
Since the dataplane is powered by ECS/EKS/EC2 which are already compliant, is it safe to assume AWS app mesh as PCI compliant?
Or when can we expect the control plane to be complaint officially?

**Comment by shubharao** [comment]
You are right that the dataplane is already certified compliant. App Mesh does not have/store any customer/app specific data, it is only coordinating the connection between running services. Ultimately, whether you are good to use depends on your organization's policy. We do plan to get PCI compliance for App Mesh.

**Comment by csbodine** [comment]
Does this announcement impact the status of this item? 
https://aws.amazon.com/about-aws/whats-new/2021/01/aws-app-mesh-achieves-pci-dss-certification/

**Comment by dfezzie** [comment]
Yes, App Mesh is now certified as a PCI DSS service! 🎉
