### ISSUE TITLE
Explicit Route Priorities 

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#77]
Envoy evaluates routes in the order they are defined in the route config. However, App Mesh APIs have no way effecting this order through the APIs - currently App Mesh does sort the routes according to length to give when it creates the Envoy route config.

In order to improve App Mesh should add a field in the API that will allow customers to set a route priority (Int) and get a deterministic ordering of routes.

**Comment by shubharao** [comment]
This feature is available in our Preview Channel. Check it out and let us know what you think! https://github.com/aws/aws-app-mesh-examples/tree/master/blogs/http-headers-and-priority
