### ISSUE TITLE
[request]: gap between upstream envoy vs app mesh

### ISSUE THREAD

**Issue by SleeperSmith** [aws/aws-app-mesh-roadmap#78]
**Tell us about your request**
Publish / keep up to date a gap analysis between upstream envoy vs app mesh. Specify which part of Envoy config / feature is supported which ones isn't / which one's on the road map / stuff that won't be included..

Especially in terms of https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#type-urls

**Which integration(s) is this request for?**
Irrelevant.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
App Mesh currently supports only a small amount of features from Envoy. I feel it'll save everyone's time from making requests asking for features in Envoy that's not yet supported.

I have made 2 of those requests so far, and I feel it's not helping asking for more as it'll eventually just end up as "feature request, support everything from envoy".

I believe it'll also help the App Mesh team to cut down on requests that flow in here? I mean, I'm sure the team already went through Envoy feature list and had reasons to / not to implement features so far.

**Are you currently working around this issue?**
Checking AWS documentation.

**Additional context**
None

**Attachments**
None

**Comment by dastbe** [comment]
Hey @SleeperSmith 

First off, thanks a lot for your interest in App Mesh! While we are working hard to grow our feature set and extend our capabilities as much as possible, we don't believe having a single issue focusing on Envoy feature parity is the right way to drive this. Besides being a fast moving target, we think having separate issues for features makes the conversation about how a feature should work (from the API down to how Envoy configuration is generated) more precise and makes our progress and timelines clearer. It also helps us better gauge demand.

I would recommend you (and anyone else!) to keep creating individual feature requests.
