### ISSUE TITLE
Unable to connect to destination on port 443 with ALLOW_ALL mesh egress filter

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-roadmap#79]
**Summary**

When allowing egress traffic to all destinations (Mesh EgressFilter type=ALLOW_ALL), network calls to destinations on port 443 are not accessible. Network calls to AWS service destinations are still accessible.

This occurs because the calls are being matched to the [Envoy filter chain match](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto#listener-filterchainmatch) App Mesh configures for AWS destinations, but requests to other destinations will fail due to the mismatch in the expected Server Name Indication (SNI), `*.amazonaws.com`.

The App Mesh team has identified a fix and will follow up on this issue once it is available.

**Steps to reproduce**
1. Create a Mesh with EgressFilter type ALLOW_ALL
2. Create a Virtual Node under that mesh with no backends (other settings do not matter)
3. Connect an Envoy to App Mesh's Envoy Management Service identified by the Virtual Node you created.
4. Attempt to connect to a network-reachable destination on port 443 that is *not* an AWS service.

Expected: You are able to connect to your destination.
Actual: Connection to your destination fails.

**Workaround**

To work around this issue, add port 443 to the list of ignored egress ports for Envoy.

For ECS, you can set this in the [Proxy Configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html).

For EKS, you can set the environment variable `APPMESH_EGRESS_IGNORED_PORTS` in the pod definition for the proxyinit container. See [Getting Started with EKS](https://docs.aws.amazon.com/eks/latest/userguide/mesh-gs-k8s.html) for more information on this definition.

For EC2, you can set `APPMESH_EGRESS_IGNORED_PORTS` using the proxy route manager script. See [Getting Started with EC2](https://docs.aws.amazon.com/app-mesh/latest/userguide/mesh-getting-started-ec2.html) for more information on this script.

**Additional Known Issues**

Although we have a fix planned for the issue reported above, please note that in some cases, traffic to specific destination ports may still be blocked or directed to an unexpected location.

For example, if you have a Virtual Node (Vnode-A) with a backend to another Virtual Node (Vnode-B), and Vnode-B is configured with portMapping settings for TCP on port 8080, all requests from Vnode-A to any destination on port 8080 will be sent to Vnode-B. If Vnode-B is configured for HTTP instead of TCP, requests will succeed to their original destination.

The reason for the intercept for TCP Virtual Node backends is due to the limited amount of information App Mesh and Envoy can match on when determining the appropriate destination. For TCP traffic, this is limited to source and destination IP address, and destination port. Today, App Mesh only matches on the destination port.

**Comment by lavignes** [comment]
This should be fixed now. Closing!
