### ISSUE TITLE
[request]: Egress only virtual nodes

### ISSUE THREAD

**Issue by rlafferty** [aws/aws-app-mesh-roadmap#83]
**Tell us about your request**
We have certain components that perform `egress` only actions to other components in the mesh.  These `egress` only components would still be defined as virtual nodes, because they need to communicate with other virtual services inside of the mesh.  When creating a virtual node, the listener attributes are _required fields_.  It would be beneficial to create some concept of egress only virtual nodes.

**Which integration(s) is this request for?**
App Mesh

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Defining listeners just to satisfy the required fields, with no intention of ever allowing this particular virtual node to receive traffic on that listener port seems arduous. Many services that run batch or background jobs with no web component would benefit from the concept of an "egress only" virtual node, because these services still need to communicate with other virtual services inside of the mesh.

**Are you currently working around this issue?**
Defining a "bogus" listener.

**Additional context**

**Attachments**

**Comment by skiyani** [comment]
Hey @rlafferty,   Thanks for reaching out. When creating a virtual node, the listener attributes are not required. Is there a doc somewhere that may have suggested it was required? 

  Here is the doc that specifies listeners are not required: https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_VirtualNodeSpec.html 

Also the cloudformation doc for virtual node listeners (also not required): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appmesh-virtualnode-virtualnodespec.html

Example: 
```
  aws appmesh create-virtual-node --mesh-name mymesh --virtual-node-name foo --spec '{}'
{
    "virtualNode": {
        "status": {
            "status": "ACTIVE"
        }, 
        "meshName": "mymesh", 
        "virtualNodeName": "foo", 
        "spec": {}, 
        "metadata": {
            "version": 1, 
            "lastUpdatedAt": 1564091512.193, 
            "createdAt": 1564091512.193, 
            "arn": "arn:aws:appmesh:us-west-2:<ACCOUNT_ID>:mesh/mymesh/virtualNode/foo", 
            "uid": "b4fcae05-aff5-4846-9fe0-4352ed8cc333`”
        }
    }
}
```

**Comment by rlafferty** [comment]
@skiyani - awesome, so is it just a difference in behavior between the console vs. making an API call via cli or SDK?

<img width="590" alt="Screen Shot 2019-07-25 at 8 50 49 PM" src="https://user-images.githubusercontent.com/6550314/61918063-fa507500-af1d-11e9-998c-f4fa8afc2b8a.png">

**Comment by skiyani** [comment]
@rlafferty - If you’d like your virtual node to be egress only you should select the “None” option in the “Service Discovery method“ section when creating a virtual node in the console. From there you can select the drop down option for Additional configuration and specify your virtual services to communicate with the other virtual node (or virtual routers) in your mesh . Hope this helps!
