### ISSUE TITLE
[request]: Allow user defined address for envoy.dog_statsd sink

### ISSUE THREAD

**Issue by joshuabaird** [aws/aws-app-mesh-roadmap#85]
**Tell us about your request**
The App Mesh Envoy image currently supports specifying a custom `STATSD_PORT` but assumes that the statsd agent is running on `127.0.0.1`.  In our environment, the dogstatsd agent runs in a separate container, thus on something other than `127.0.0.1`.  For this reason, we are having to create our own container that wraps the App Mesh Envoy container and specifies a custom `ENVOY_STATS_SINKS_CFG_FILE` that contains the IP of the dogstatsd agent.  It would simplify our deployment of App Mesh if we could simply provide this IP as an environment variable. 

**Are you currently working around this issue?**
Wrapping the Envoy container with our own container which contains a custom `ENVOY_STATS_SINK_CFG_FILE`.

**Comment by lavignes** [comment]
This issue seems to have not been updated. This configuration option does exist now: https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html#envoy-dogstatsd-config
