### ISSUE TITLE
[request]: Support for specifying additional configuration for envoy listeners created by ADS

### ISSUE THREAD

**Issue by joshuabaird** [aws/aws-app-mesh-roadmap#86]
**Tell us about your request**
We want to use Datadog APM with App Mesh/Envoy.  Support for Datadog is included in Envoy 1.9.0, but requires additional static configuration as detailed below.

**Which integration(s) is this request for?**
ECS/Datadog.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As indicated above, we would like to use Datadog APM with Envoy/App Mesh.  Detailed instructions for this configuration can be found here:

https://docs.datadoghq.com/tracing/setup/envoy/

The configuration requires a) a static cluster configuration, b) a static tracing configuration and c) listener configuration.

Configuring an additional static cluster and tracer is simple enough by wrapping the Envoy container that AWS provides to add this additional configuration to `envoy.yaml`.  

The problem is the listener configuration (to support `envoy.http_connection_manager`).  This configuration is defined on the `listener` which is provided dynamically from App Mesh via ADS.  Because of this, we are unable to add the necessary configuration ourselves.

**Are you currently working around this issue?**
We have no APM tracing for App Mesh/Envoy.  

**Additional context**
X-Ray is not an option at this time.

**Comment by kiranmeduri** [comment]
Can you provide what additional configuration you need to add? Currently App Mesh already sets the following

```
{
    "name": "envoy.http_connection_manager",
    "config": {
        "tracing": {
            "operation_name": "EGRESS"
        },
        "http_filters": [
            {
                "name": "envoy.router"
            }
        ],
        "rds": {
            "route_config_name": "rds_egress_http_8080",
            "config_source": {
                "ads": {}
            }
        },
        "stat_prefix": "egress"
    }
}
```

Looking at DataDog docs this should work to get the traces. 

Thanks

**Comment by joshuabaird** [comment]
@kiranmeduri Sorry - you are correct.  Datadog tracing is working as expected.  I did not realize the `http_connection_manager` was configured by App Mesh.

**Comment by kiranmeduri** [comment]
No worries thanks for confirming. Please reopen if you see any other issues.
