### ISSUE TITLE
Integration with EKS

### ISSUE THREAD

**Issue by jamsajones** [aws/aws-app-mesh-roadmap#9]
The integration will happen primarily with a controller running in the customer's cluster on the master instances, managed by EKS.  The controller will watch the Kubernetes API of the customer's cluster and react to certain objects being created or modified.  It will create the necessary components in AppMesh and CloudMap. 

Initial support will be for a single AppMesh mesh and a single CloudMap namespace per cluster (though many clusters can share a mesh/namespace).  Customers can provide an existing mesh/namespace as well.

An additional component that will be used on the customer's worker nodes is the App Mesh CNI(https://github.com/awslabs/aws-app-mesh-examples/issues/15).  Its responsibility is to enter the network namespace of a new pod and set up iptables rules to route incoming and outgoing traffic through envoy.  This takes the place of an init container, and is preferred to avoid having to run privileged containers altogether. 

Optionally, a mutating admission webhook could be employed to inject envoy as a sidecar container into pods that are launched in the cluster.

**Comment by coultn** [comment]
See here: https://github.com/aws/aws-app-mesh-controller-for-k8s
https://github.com/aws/aws-app-mesh-inject
