### ISSUE TITLE
App Mesh API Go SDK HttpMethod enum values incorrect casing

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-app-mesh-roadmap#93]
As at [AWS SDK v1.23.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.23.3) the HttpMethod enum values are incorrectly lowercased: https://github.com/aws/aws-sdk-go/blob/1f5f7a448b2ef1e5ef20489682e0a115b32208a9/service/appmesh/api.go#L8287-L8314.
The [documentation](https://docs.aws.amazon.com/app-mesh/latest/APIReference/API_HttpRouteMatch.html) is similarly incorrect.
The live API accepts the HTTP method in uppercase (e.g. `POST`).

**Comment by lavignes** [comment]
Hey @ewbankkit thanks for pointing this out.
We're working to get this fixed as soon as possible.

**Comment by skiyani** [comment]
Hey @ewbankkit the fix had been merged into the Go SDK: https://github.com/aws/aws-sdk-go/releases/tag/v1.23.4

Please let us know if you find any other issues!
